### ISSUE TITLE
Décrire qui travaille sur le projet, a quel rôle et les canaux de communication

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#1]

**Comment by thom4parisot** [comment]
Ça se présente sous quelle forme ? Tu pensais à quoi : footer, page à part, README ou autre ?

**Comment by DavidBruant** [comment]
Readme. Dire qui travaille et contacter qui quand on a quel problème. Parler du Trello (même si on ne l'ouvre pas)

**Comment by thom4parisot** [comment]
👍

**Comment by vinber** [comment]
Peut-être que le readme peut effectivement décrire et expliquer un peu mieux le projet, en plus de qui fait quoi ?

Description du projet / 
J'ai commencé ce "dessin" pour mieux comprendre et c'est en lien avec les actuelles discussions, il me semble.

![budget](https://cloud.githubusercontent.com/assets/890869/22852711/9f5717b8-f042-11e6-8f89-b8a913ccdc77.png)

Blablabla type / L'enjeu du projet est de "lier" les données M52 normalisées avec les données aggrégées qui représensent une vision plus usuelle des questions budgétaires.

**Comment by DavidBruant** [comment]
> Peut-être que le readme peut effectivement décrire et expliquer un peu mieux le projet, en plus de qui fait quoi ?

oui. Déplaçons ça dans une autre issue, c'est un sujet un peu différent => https://github.com/dtc-innovation/dataviz-finances-gironde/issues/52

**Comment by DavidBruant** [comment]
Lié à la transmission. Pas besoin de le suivre dans github
