### ISSUE TITLE
les sommes des DF actions sociales par publics et par prestations sont différentes

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#100]
https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF
Dans le titre il est indiqué qu'il s'agit de la même chose mais avec des découpages différents alors que les sommes sont différentes. il faut vérifier les sommes ou changer le texte

**Comment by ClementineHahn** [comment]
Problème noté en effet. C'est une conséquence directe de la non finalisation du tableau des formules agrégées. Il sera nécessaire de travailler /finaliser ce tableau d'abord avant toute vérification/correction des sommes et des textes. On se rattaque à ce sujet au prochain sprint avec Laurence.

**Comment by DavidBruant** [comment]
A voir avec la dernière version des formules
