### ISSUE TITLE
utilisation du tableau source texte

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#102]
Je viens de faire une passe sur le tableur donnant des définitions pour les agrégats du compte administratif. 
https://docs.google.com/spreadsheets/d/1RQ6YAhFlFZaamvl6HpUxH_4MaG7Yg8l45pdTey14tOU/edit#gid=1852965930
apparemment la dataviz n'en fait pas une lecture directe car je ne vois pas mes modifications.
Si besoin je peux essayer de systématiser leur présentation pour en faciliter l'affichage. 
Genre une phrase de 150 caractères pour résumer. 
Retour à la ligne
un paragraphe pour détailler. 
Retour à la ligne
un lien vers une source explicative

**Comment by DavidBruant** [comment]
La mise à jour des contenu est manuelle et va le rester a priori.
L'uniformisation éditoriale a été décidée ailleurs si mes souvenirs sont exacts.
