### ISSUE TITLE
Navigation dans les pages de l'agrégé

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#103]
Sur une page de détail de navigation dans le tableau agrégé je ne vois pas de lien pour remonter d'un niveau dans la navigation

**Comment by ClementineHahn** [comment]
Le module qui permettra de naviguer entre les niveaux de l'agrégés (total dépenses ou recettes suivt où on est + niveau immédiatement supérieur) est sur la to do des MAJ à apporter. (cf Issue *MAJ avt le 13 Avril*)
Ce module est une proposition, il faudra des test pour vérifier quelle est la meilleure façon d'accompagner les utilisateurs à la navigation.

**Comment by DavidBruant** [comment]
A voir l'articulation avec le système de navigation du site gironde.fr

**Comment by DavidBruant** [comment]
Il y a de la navigation depuis #229.
Je considère cette issue résolue. Créer d'autres issues si des problèmes liés à la navigation actuelle arrive.
