### ISSUE TITLE
Paramétriser l'URL des données M52

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#11]
https://github.com/dtc-innovation/dataviz-finances-gironde/pull/9#discussion_r96237659

**Comment by thom4parisot** [comment]
Surtout je me disais : y'a peut-être une même source de données pour deux composants différents.

Typiquement (?) :

```jsx
export default (props) => {
  const data = await fetch(props.url);

  return (<section>
    <Sunburst data={data} />
    <Sunburst data={m52.simplify(data)} />
  </section>);
}
```

**Comment by DavidBruant** [comment]
Pas pertinent.
Une meilleure idée pourrait être de charger tous les CA pour faire une comparaison avec tous
