### ISSUE TITLE
le lien de navigation des pages de second niveau renvoient vers l'accueil

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#115]
En cliquant depuis la page #!/total on arrive par exemple sur la page de détail concernant les dépenses de fonctionnement #!/finance-details/EXPENDITURES. Depuis cette page le lien de retour disponible nous propose de revenir à l'accueil et pas à la page #!/total qui est la page de niveau supérieur. Il devrait y avoir un lien retour qui prenne en compte le choix de l'année sélectionné par l'utilisateur lorsque cela est possible

**Comment by DavidBruant** [comment]
Considération de navigation. Je le considère duplicat de #103
