### ISSUE TITLE
[Pages Finances Détails] Dans l'histogramme d'évolution, faire apparaitre les sous-ensembles pour chaque année 

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#121]
A la manière de l'histogramme réalisé pour la page Solidarités, il est demandé pour chaque page "Détail-Finance" de faire apparaitre dans l'histogramme d'évolution les sous-ensembles de dépenses ou de recettes pour chaque année.

**Comment by DavidBruant** [comment]
Et faire les légendes aussi

**Comment by DavidBruant** [comment]
Et cliquable aussi

**Comment by DavidBruant** [comment]
Manque plus que le "cliquable"

**Comment by DavidBruant** [comment]
Les sous-ensembles sont cliquables depuis https://github.com/dtc-innovation/dataviz-finances-gironde/pull/245
