### ISSUE TITLE
[Pages Finances Détails] Ajout d'une légende sous l'histogramme pour définir les sous-ensembles

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#122]
De la même manière de ce qui a été fait pour l'histogramme d'évolution des dépenses de la page solidarité : toutes les pages Finances Détails doivent avoir une légende pour comprendre toutes les parties qui composent l'évolution d'une dépense ou d'une recette.

 Il est attendu jusqu'à 9 sous-parties pour une colonne de l'histogramme. Certaines seront trop petites pour être lisibles. C'est attendu. La légende doit permettre d'y remédier.

**Comment by DavidBruant** [comment]
Les légendes feront partie de #121
