### ISSUE TITLE
[Pages Finances Détails] Rendre cliquable les sous-parties de l'histogramme pour permettre la navigation

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#123]
[Pages Finances Détails] 
Les sous-parties qui composent chaque colonne de l'histogramme doivent être cliquables. 

Cet histogramme devient donc un élément de navigation à l'intérieur des dépenses et des recettes. 

Certaines parties seront trop petites pour permettre de cliquer facilement dessus. La légende qui sera ajoutée permettre pour l'instant de pallier à ce problème.

**Comment by DavidBruant** [comment]
Partie de #121
