### ISSUE TITLE
[Pages Finances Détails] Ne plus afficher la section éclatée des sous-ensembles dépense ou recette et de leurs définition

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#125]
![capture d ecran 2017-05-10 a 3 18 57 pm](https://cloud.githubusercontent.com/assets/23077793/25955207/da5189c2-3668-11e7-9c9f-b8d31243f3cb.png)

Il a été demandé par la direction des finances de ne plus garder cette section qui présente tous les sous-ensembles d'une dépense ou d'une recette. 

La visualisation de ces sous-ensembles passera désormais par l'histogramme d'évolution. Par contre le fait de ne plus afficher cette partie enlève la possibilité de visualiser à l'avance les définitions des différentes sous-parties de la dépense/recette.

**Comment by DavidBruant** [comment]
Après discussion avec Renaud, il est ressorti que dupliquer, c'est bien parce que les visiteurs ne vont peut-être pas prendre l'initiative de cliquer sur un graphique ou une légende.

A minima, il faudrait trier les éléments par ordre décroissant et faire que le montant apparaisse dans tous les cas. Peut-être virer la description. Et rendre l'ensemble plus petit.

**Comment by DavidBruant** [comment]
Voir #160
