### ISSUE TITLE
 [Pages Finances Détails] - Ds la viz type pie-chart, situer la dépense visualisée par rapport au DI-DF ou RI-RF concerné

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#126]
Aujourd'hui le pie-chart prend comme référence de total soit : le total des dépenses , soit le total des recettes. Il faut changer cette référence pour que le total du pie-chart représente le DI, DF RI, RF concerné

**Comment by DavidBruant** [comment]
Remplacé par #342
