### ISSUE TITLE
[Pages Finances Détails] Ajouter dans l'histogramme les totaux des sousparties de colonne. 

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#129]
Chaque sous-partie de l'histogramme doit être caractérisé par un total. Si proportionnellement, l'espace du sous-ensemble ne permet pas d'afficher la typo qui donne le montant correctement, faire une règle pour cacher le montant. 

>> carte peut clair sur la "règle à adopter" on peut en discuter de visu

**Comment by DavidBruant** [comment]
![capture du 2017-09-14 17-31-08](https://user-images.githubusercontent.com/165829/30438859-94d21ce6-9972-11e7-938d-27bea89bfbc0.png)

On est bon
