### ISSUE TITLE
[Animation Construction budget] Corriger la nature et le montant des blocs de l'animation d'après les retours de métier finance

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#133]
Je n'ai pas pris de notes plus précises sur ce sujet, Laurence devait fournir par mail à David Bruant la denière version avec les blocs à animer ainsi que leur montant. 

David, je (clémentine) n'ai pas pris de notes plus en avant sur les changements d'animation à faire notamment autour de l'apparition de l'épargne comme une non-dépense des recettes de fonctionnement. Tu m'as dit avoir les idées claires à ce sujet. Dis-moi si besoin de réajuster ce sujet avec Isabelle et/ou Laurence

**Comment by DavidBruant** [comment]
On est bon sur l'animation
