### ISSUE TITLE
compatibilité navigateur

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#144]
La page home ne s'affiche pas avec Internet Explorer 11

**Comment by thom4parisot** [comment]
@datalocale ah, à tout hasard pourrais-tu joindre une capture d'écran/copié-collé du message d'erreur dans la console d'IE11 ?

cf. [https://msdn.microsoft.com/en-us/library/dn255006(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/dn255006(v=vs.85).aspx)

**Comment by datalocale** [comment]
Depuis la console on voit une erreur qui pointe vers la methode WeakMap du fichier public-bundle.js
La cible de compatibilité c'est au moins IE10 et IE11
![erreurie](https://cloud.githubusercontent.com/assets/1333196/26715439/0b97a8b8-4776-11e7-8131-16e3bf4ba567.PNG)
![erreurie-2](https://cloud.githubusercontent.com/assets/1333196/26715441/0bedc8a6-4776-11e7-8cf5-797663357020.PNG)
![erreurie-11](https://cloud.githubusercontent.com/assets/1333196/26715440/0bac5c40-4776-11e7-9a18-5f669f7b06e5.PNG)

**Comment by DavidBruant** [comment]
Ok, on est sur des fonctionnalités qui ne sont pas supportées nativement, mais si c'est le seul problème, il sera facile à résoudre (grâce à l'ajout de polyfills).

**Comment by akakeronos** [comment]
Il reste un message d'erreur qui bloque l'affichage 
L’objet ne gère pas la propriété ou la méthode « startsWith »
Fichier : public-bundle.js, ligne : 671, colonne : 694

**Comment by DavidBruant** [comment]
L'erreur avec startsWith est plus surprenante, car cette fonction est sensée est toujours présente dans les polyfills.
Il est possible que la version de IE testée n'aie pas une `User-Agent` string reconnue par polyfill.io

**Comment by thom4parisot** [comment]
@DavidBruant le fait que les polyfills soient appelés avec `https://cdn.polyfill.io/v2/polyfill.min.js?features=WeakMap,Promise,fetch` (cf. [`public/index.html#12`](https://github.com/dtc-innovation/dataviz-finances-gironde/blob/44eb7cc0b896b6b574b5c3e9e56c538628a6b557/public/index.html)) pourraient empêcher que ça soit le cas ?

En forçant le _User Agent_ à IE11, le polyfill pour `startsWith` n'est effectivement pas envoyé.
> https://cdn.polyfill.io/v2/polyfill.js?features=WeakMap,Promise,fetch,String&ua=Mozilla/5.0%20(Windows%20NT%206.3;%20Trident/7.0;%20rv:11.0)%20like%20Gecko

En enlevant le paramètre `features=...` ou en le suffixant par `,String.prototype.startsWith`, le polyfill de `startsWith` apparaît bien.

_Ref_ [polyfill.io features](https://polyfill.io/v2/docs/examples#flags)
_Ref_ [IE 11 User Agent](https://blogs.msdn.microsoft.com/ieinternals/2013/09/21/internet-explorer-11s-many-user-agent-strings/)

**Comment by DavidBruant** [comment]
@oncletom bien vu !

J'avais essayé avec le ua de IE11, mais sans `features=WeakMap,Promise,fetch` et startsWith était présent. Peut-être qu'effectivement quand on liste explicitement, il enlève les polyfills chargés par défaut.
Je vais essayer d'ajouter le *feature set* `default`, voir si ça résoud le problème.

**Comment by DavidBruant** [comment]
J'ai rajouté `default`. On avance. Il manque désormais `Array.prototype.includes`.
Le chargement sur IE11 révèle qu'il va falloir faire un peu de CSS aussi.

![bug css ie11](https://user-images.githubusercontent.com/165829/27949836-83756240-62ff-11e7-8132-26c1a9ed1053.png)

**Comment by akakeronos** [comment]
aujourd'hui sur la version intégrée au site de pre-prod je n'ai rien qui s'affiche.
La console affiche les erreurs suivantes :  
SCRIPT5022: HierarchyRequestError
Fichier : polyfill.min.js, ligne : 3, colonne : 3585

SCRIPT438: L’objet ne gère pas la propriété ou la méthode « assign »
Fichier : dataviz-finance-gironde-fr-bundle_1.datavizscript, ligne : 675, colonne : 235

SCRIPT5: Accès refusé.
Fichier : polyfill.min.js, ligne : 3, colonne : 2706

**Comment by thom4parisot** [comment]
@DavidBruant ça sent l'absence d'`Object.assign`, non ?

**Comment by DavidBruant** [comment]
> @DavidBruant ça sent l'absence d'Object.assign, non ?

Oui, mais c'est surprenant vu qu'il était là, avant.

@akakeronos dans le "bloc HTML5", il y a deux lignes `<script src="">`. Une pour le JS de l'application et une qui charge un script venant de `https://cdn.polyfill.io`.
Si mes souvenirs sont exacts, la ligne devrait être exactement la suivante : 
`<script crossorigin="anonymous" src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.includes,WeakMap,Promise,fetch"></script>`

Si ce n'est pas exactement cette ligne, remplace la ligne actuelle par celle-ci voir si ça corrige le problème.

**Comment by DavidBruant** [comment]
"sur ma machine", je n'observe pas le problème.

![screenshot ie11](https://user-images.githubusercontent.com/165829/31447502-6ceb28e0-aea2-11e7-8ccc-7fbe3fd57df3.png)

Est-il parti ? Est-il spécifique à l'intranet du Département ?

**Comment by DavidBruant** [comment]
Hmm... Peut-être une piste ici : https://github.com/Financial-Times/polyfill-service/issues/239#issuecomment-308472489

**Comment by DavidBruant** [comment]
Après discussion avec @akakeronos il semblerait que le problème des polyfills avec IE11 ne s'observe que sur le parc de machines du CD33 où IE11 est configuré d'une certaine manière empêchant certaines requêtes cross-origin (ce qui apparemment n'était pas le cas au début de l'été 2017). 
A cet instant, il n'est pas clair si le problème vient d'une mise à jour récente de IE11 ou d'un changement de configuration récent.

Ca serait beaucoup trop de taf de comprendre le fond du problème surtout pour un navigateur qui va disparaitre bientôt. Je vais juste rajouter les polyfills pour IE11 hardcodés (source : 
https://cdn.polyfill.io/v2/polyfill.js?features=default,Array.prototype.includes,WeakMap,Promise,fetch&ua=ie/11&flags=gated )
Ca rajoute ~80kb de code (15kb gzippés), ce qui est acceptable

**Comment by DavidBruant** [comment]
Un premier jet a été effectué sur ce sujet : #312  
Si des problèmes spécifiques apparaissent, créer de nouvelles issues spécifiques à chaque problème de compatibilité
