### ISSUE TITLE
[HOME] les titres de niveau 1 sont en lettres capitales

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#145]
Personnellement je ne suis pas fan des titres en majuscules

**Comment by thom4parisot** [comment]
@datalocale on me corrigera peut-être mais il semblerait que l'implémentation actuelle suive la charte du site gironde.fr. 

<img width="886" alt="screen shot 2017-06-01 at 16 30 21" src="https://cloud.githubusercontent.com/assets/138627/26684631/c28e574a-46e7-11e7-9aac-d08a7c25d519.png">

Il me semblait avoir compris que la dataviz suivait la charte du site gironde.fr — on est d'accord ?

**Comment by datalocale** [comment]
oui tu as raison. Tant pis pour moi :)
