### ISSUE TITLE
harmoniser l'affichage des sommes d'argent

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#146]
Sur la page #!/focus/SOLIDARITES il y a plusieurs syntaxes pour écrire des sommes en million.
Je propose d'harmoniser cette syntaxe sous la forme millions d'€ avec un espace entre le nombre et le mot
par exemple : 244 millions d'€

**Comment by DavidBruant** [comment]
De manière générale, il faut harmoniser l'affichage des sommes d'argent sur toutes les pages. Il y a parfois des millions et parfois seulement des milliers.
A ce stade et sauf erreur, je ne vois que 2 contextes : 
* contexte long (au milieu d'une phrase, ou de manière générale hors des graphiques)
* contexte court (à l’intérieur d'un morceau de *stack chart* par exemple)

Chacun de ces deux contextes exigent un traitement différent, je pense. L'autre dimension, c'est de décider : 
* quel niveau de précision on affiche dans chaque contexte (nombre de chiffres significatifs, utilisation de la virgule ou pas)
* quel est le texte qu'on l'on affiche selon le contexte (m, M, k, K, million, etc. + €, euros, euro, etc.) 

Quelle est la décision prise à ce sujet pour la charte graphique du Département ? Est-ce que le service des finances ont une habitude là-dessus ?

**Comment by DavidBruant** [comment]
L'opinion de Renaud sur le sujet est qu'il existe autant de contexte différent que de manière pertinentes d'écrire des sommes. A faire contexte par contexte (mais être consistent quand le contexte est identique)

**Comment by DavidBruant** [comment]
Le sujet de l'affichage des sommes d'argent revient pas mal. Je réouvre. 
Ca ne sera pas "harmonisé" au sens d'"uniforme sur tout le site", mais il y a des morceaux communs
