### ISSUE TITLE
mise en forme des textes page focus solidarité

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#147]
Les blocs qui décrivent les types d'aides accordées par type de publics mériteraient un peu de respiration.
Je propose d'ajouter des retours à la ligne et des parties de texte en gras pour faciliter la lecture.
Je propose également d'ajouter un peu d'espace entre la barre indiquant le montant du dispositif et le texte le décrivant. Le même espace que celui qui existe entre la fin du texte et les blocs gris du dessous.
Il faudrait également ajouter un peu d'espace entre les blocs gris et le bouton en savoir plus

**Comment by DavidBruant** [comment]
Cette discussion sera inefficace par écrit. Discutons-en quand on se voit avec Renaud.

**Comment by DavidBruant** [comment]
#158
