### ISSUE TITLE
manque un texte dans le bloc 218 millions personnes handicapées de la page focus

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#148]
Le chiffre de 218 M étant différent du chiffre du dessus (207M ?? c'est pas normal d'ailleurs) il faudrait expliquer cette différence

**Comment by DavidBruant** [comment]
La différence est due au fait qu'un des nombre (218M) est hardcodé et l'autre (207M) est calculé depuis les formules d'agrégation.
Je vais poser la question à la DFI

**Comment by DavidBruant** [comment]
Le bloc a été ajouté, le problème de montant reste. Je vais corriger #100 et il faudra faire un atelier avec la DFI sur ce sujet

**Comment by akakeronos** [comment]
Corrigé
