### ISSUE TITLE
manque un texte dans le bloc 168 millions enfance de la page focus solidarité

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#149]
Les chiffres du bloc gris étant potentiellement un sous-ensemble de l'ensemble de la dépense lié au public enfance il faut ajouter un texte pour expliquer à quoi se rapporte ce chiffre.

**Comment by DavidBruant** [comment]
J'ai l'impression que cette issue est plus un problème de contenu qu'un problème de code ?

**Comment by DavidBruant** [comment]
Je ne comprends pas ce qu'il faut faire. Ou peut-être que c'est déjà corrigé. Je ferme. Recréer une issue plus clair si ce besoin ré-emerge.
