### ISSUE TITLE
manque un bloc gris dans la section personnes en insertion de la page focus solidarité

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#150]
Il faut ajouter un bloc pour le nombre de bénéficiaires du RSA pour homogénéiser avec les autres sections.
Le nombre de référence provenant de DIgDash pour 2016 est de 61394

**Comment by DavidBruant** [comment]
J'ai l'impression qu'il s'agit plus d'un problème de contenu que de code. Je vous laisse organiser les ateliers nécessaires et revenir vers moi, l'intégration sera facile.

**Comment by DavidBruant** [comment]
Fait
