### ISSUE TITLE
source de données contextuelles

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#151]
Un jeu de données reprenant le nombre de bénéficiaires de l'action sociale par commune est disponible sur datalocale : https://www.datalocale.fr/dataset/synthese-des-beneficiaires-de-laide-sociale-en-gironde1

**Comment by DavidBruant** [comment]
A cet instant, j'obtiens une erreur 404 quand je vais sur ce lien ?
Dans tous les cas, il semble qu'il s'agit d'une problèmatique de contenu. Je vous laisse faire les ateliers nécessaire pour savoir comment intégrer ce contenu dans l'outil actuel.

**Comment by DavidBruant** [comment]
Plus d'actualité
