### ISSUE TITLE
harmonisation des comportements d'exploration des histogrammes

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#152]
est-il possible d'étendre le comportement à venir des histogrammes des pages d'exploration de l'agrégée à celui (ou ceux) des pages focus ?
Sur la page #!/focus/SOLIDARITES cliquer sur un sous-ensemble d'une année donnée m'enverrait vers la page détails de l'agrégé correspondante. 
Fausse bonne idée ?

**Comment by DavidBruant** [comment]
Oui oui complètement. Le fait que les deux diagrammes soient différents est une cicatrice qui permettait de livrer quelque chose le 13 avril (voir #113). Il avait fallu faire un copier/coller pour aller plus vite à un moment où il n'était pas très clair de la quantité de commun et de différence entre ces deux histogrammes. C'est prévu d'unifier le tout.
Je pense que je vais faire très bien l'histogramme des pages d'élément financier (qui est plus riche plus complet), puis extraire dans son propre composant et réutiliser ce composant dans la page de focus solidarité.

**Comment by DavidBruant** [comment]
> Sur la page #!/focus/SOLIDARITES cliquer sur un sous-ensemble d'une année donnée m'enverrait vers la page détails de l'agrégé correspondante.

Les focus sont sensés mettre en valeur les actions menée dans l'année précédente. Je doute que ça soit une bonne idée ou possible (à moins de garder les focus de toutes les années ?)

Je ferme l'issue. Réouvrir une autre issue plus clair s'il y a un consensus clair sur ce besoin.
