### ISSUE TITLE
navigation depuis la page focus solidarité

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#153]
Il me manque un lien retour pour revenir à la home depuis la page focus solidarité

**Comment by DavidBruant** [comment]
Toutefois, la fonctionnalité native du bouton "back" du navigateur fonctionne. Est-ce suffisant ? (question complètement ouverte, je n'en ai aucune idée)

**Comment by DavidBruant** [comment]
Considération de navigation. Dupe de #103
