### ISSUE TITLE
problème de chargement des données lors de l'appel direct d'une page d'exploration

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#154]
Si j'ouvre dans un navigateur fenêtre privée un lien direct vers une sous-partie de l'exploration de la navigation dans l'agrégée la page s'affiche d'abord sans données puis progressivement les données apparaissent. De plus il me semble que la taille des barres de l'histogramme et les polices sont plus grosses.

Test avec https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-4

**Comment by DavidBruant** [comment]
Le comportement que tu décris correspond à celui qui est codé et celui qui était attendu quand j'ai codé le chargement des données. Ce sujet n'a jamais vraiment été discuté, il n'est donc pas clair si le comportement actuel est un "problème".

A noter qu'une fois le chargement d'une page effectué, toutes les autres sont instantanées sans affichage partiel intermédiaire. La "souffrance" d'un affichage partiel-mais-correct ne dure donc que 5-10 secondes et seulement pour les personnes qui arrivent directement par un lien d'une page élément financier.

Compte tenu de la contrainte de déploiement sur le site gironde.fr (un site "single page" chargé depuis une seule page Drupal), il est difficile de faire mieux sans déployer beaucoup d'effort (du côté de ce projet et peut-être du côté du CD33).

A discuter

**Comment by DavidBruant** [comment]
A priori, il s'agit du comportement attendu.
