### ISSUE TITLE
MAJ Focus Solidarités pour le 12/06/17

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#155]
- [x] sous le bloc texte "personnes en insertion"ajouter un bloc "chiffre clé" (comme modèle 229 millions d'euros pr le RSA...)  et y inscrire dedans "X bénéficiares du RSA"
- [x] déplacer l'histogramme "Dépenses de solidarités" pour le remonter avant la partie "les publics"

**Comment by akakeronos** [comment]
61 588 bénéficiaires du RSA
