### ISSUE TITLE
retours utilisateurs sur le camembert présentant le contexte des sommes dans l'exploration du budget

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#171]
C'est plus une remarque qu'une issue mais les premiers retours utilisateurs sur les outils de navigation font remonter une difficulté de lisibilité et de compréhension du camembert présentant la part des dépenses présentées avec celles de niveaux supérieurs. A travailler en atelier avec des utilisateurs

**Comment by DavidBruant** [comment]
Oui. Le camembert actuel n'est pas le définitif. Du travail sur ce sujet sera réalisé à l'occasion de #160.
