### ISSUE TITLE
Changer le titre de l'aperçu des lignes M52 sur les pages feuilles 

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#173]
A l'usage, on ne comprend que les lignes M52 sur les pages feuilles ne correspondent qu'à la sous-partie agrégée lu. 
Il faut donc plus rédiger le titre et changer ~~"Lignes M52 correspondantes en 2016"~~ mais plutôt : **"Consultez ces données en détail (norme comptable M52)"**

![capture d ecran 2017-06-15 a 9 52 33 am](https://user-images.githubusercontent.com/23077793/27171365-8ad06e54-51b1-11e7-96e4-d43c51363f1d.png)

**Comment by DavidBruant** [comment]
Je pense que tu peux gérer cette issue et en faire une PR ;-)
N'hésite pas à me dire si ça te pose plus de problème que les fois précédentes.

**Comment by ClementineHahn** [comment]
Effectivement j'avais fait cette issue avant que tu m'expliques. Je m'en charge ! :)
