### ISSUE TITLE
Changer le libellé de l'appel à téléchargement du budget CSV M52

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#174]
changer le titre ~~" Télécharger toutes les données Open Data à la norme M52 au format CSV"~~ 
pour " Téléchargez le budget complet en open data à la norme M52"

![capture d ecran 2017-06-15 a 10 02 01 am](https://user-images.githubusercontent.com/23077793/27171548-33a0f562-51b2-11e7-946c-b899d22efa1c.png)

**Comment by DavidBruant** [comment]
@ClementineHahn dans quelle page ? Cette issue a-t-elle toujours un sens ?
