### ISSUE TITLE
Tâches liée au déploiement sur gironde.fr

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#179]
- [ ] enlever la classe `r-video` au parent de `.cd33-finance-dataviz` (il restera un problème de footer superposé)
- [ ] héberger l'image de la home sur gironde.fr et référencer le bon lien

**Comment by akakeronos** [comment]
J'ai crée un média de type dataviz sur le site de préprod http://gironde-preprod.cg33.fr/media/1938
Ensuite dans le bloc html5 j'ai référence le nom du script qu'il sera peut-être possible de deviner
/sites/default/files/dataviz/dataviz-finance-gironde-fr-bundle_0.datavizscript (à voir si on peut éviter ce renommage de fichier à l'upload)
J'ai ensuite remplacé la balise style et son contenu par une balise link référençant la feuille de style css
Actuellement le type image associé au type de contenu drupal ne permet pas d'associer des extension svg mais cela sera corrigé. Les chemins des images seront donc du type
/sites/default/files/dataviz/bonhomme.svg
Les fichiers de données source sont également disponible avec la même racine
/sites/default/files/dataviz/cedi_2014_CA.csv
Je ne sais plus si les fichiers des textes des définitions doivent être chargés également comme média externe ?

**Comment by DavidBruant** [comment]
Nous avons réussi cet été à déployer sur la preprod de gironde.fr

La question du déploiement a beaucoup changé depuis le dernier commentaire. Je ferme cette issue. Ouvrir des issues spécifiques si des problèmes spécifiques apparaissent
