### ISSUE TITLE
Changer le titre des pages focus sur la Home et pour chaque page focus

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#181]
- [ ] Changer : ~~"Un territoire de solidarités"~~ pour **" Solidarités"**
- [ ] Changer : ~~"Des investissements ambitieux"~~ pour **"Investissements"**
- [ ] Changer : ~~"Une action de proximité~~pour **"Présence sur le territoire"**

**Comment by DavidBruant** [comment]
T'sais quoi ? Je vais t'apprendre à trouver où c'est dans le code et à le changer toi-même :-)

dix-huit heure,
light as feather?
