### ISSUE TITLE
problème de navigation dans les sections de l'agrégé

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#185]
Depuis la mise à jour d'hier il me semble qu'il n'est plus possible d'accéder aux feuilles de navigation de l'agrégé.
Les liens disponibles depuis cette page par exemple, bien que renvoyant vers les sous-sections ne permettent pas leur affichage

https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-6-1-1

**Comment by DavidBruant** [comment]
En effet.
J'ai constaté un autre bug qui était que les lignes de la M52 ne s'affichaient pas dans la navigation par M52. Corrigé dans la même PR #189
