### ISSUE TITLE
Mise en forme du texte

### ISSUE THREAD

**Issue by vinber** [datalocale/dataviz-finances-gironde#192]
https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/explorer

*" une l’épargne brute en nette amélioration, fruit notamment d’une gestion rigoureuse des dépenses de fonctionnement une réduction du besoin de financement par emprunt qui entraîne une baisse du ratio de financement en % des recettes de fonctionnement indicateur de la performance financière"*

- une **l’**épargne brute en nette amélioration, fruit notamment d’une gestion rigoureuse des dépenses de fonctionnement,
- une réduction du besoin de financement par emprunt qui entraîne une baisse du ratio de financement en % des recettes de fonctionnement indicateur de la performance financière

**Comment by DavidBruant** [comment]
On se voit mercredi. On va en profiter pour que je te rende autonome sur des changements de ce type ^^

**Comment by DavidBruant** [comment]
@vinber si je comprends bien, l'idée ici, c'est de transformer le texte en 2 bullet point ?

**Comment by DavidBruant** [comment]
Il s'agit aussi de #286
