### ISSUE TITLE
Coquille

### ISSUE THREAD

**Issue by vinber** [datalocale/dataviz-finances-gironde#193]
https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/REVENUE

Les recettes ont augmenté en 2016 du fait de l'aug**e**mentation du taux de fiscalité sur les propriétés bâties consenties pour faire face à l'augmentation des dépenses d'actions sociales.

**Comment by DavidBruant** [comment]
Yes, je t'invite à modifier le Google Spreadsheet des contenus temporels

**Comment by vinber** [comment]
ok
