### ISSUE TITLE
Version mobile-friendly

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#196]
Il était initialement décidé pour simplifier de ne pas s'occuper de la version mobile.
Il semble qu'aujourd'hui soit le bon moment pour s'en occuper puisque les contenus sont stabilisés.

Une version mobile devrait être assez facile à produire puisque le HTML et CSS sont assez simples. Les tailles sont données la plupart du temps en `%`, `em` ou `vh/vw`, donc l'adaptation devrait être assez facile.

Points qui peuvent poser difficulté : 
* (home) L'appetizer principale devient facilement une ellipse sur des largeurs plus petites
    * Va falloir trouver une solution
* (focus et élément financier) Les stackchart en SVG
    * Une solution facile peut être de mettre moins de colonnes
* (explorer) l'animation
    * Elle n'apparait pas du tout sur mobile

Le reste va demander un peu de travail, mais rien de compliqué a priori.

Contraintes du site gironde.fr : 
* breakpoint à 640px

**Comment by DavidBruant** [comment]
Pour le stackchart, mettre la légende à droite s'il y a la place (large width)

**Comment by DavidBruant** [comment]
Il a été demandé que le même contenu soit disponible sur mobile que sur desktop. Pour le gros des contenus, ça n'est pas un problème.

## (focus et élément financier) Les stackchart 

Pour ces éléments, il n'est donc pas possible de juste virer des colonnes. Proposition : 
* width>1050px, donner une largeur de 800px au svg et de 200px pour la légende à droite
* width>800px, donner une largeur de 800px au svg + légende en-dessous
* width>600px, donner une largeur de 100% au svg + légende en-dessous
* width<=600px, tourner le stackchart de 90° (années à gauche, montants en haut) + donner une hauteur < 100% au svg + légende en-dessous

## (explorer) l'animation 

Aucune idée. Rendre cet objet disponible sur un petit écran ressemble à la quadrature du cercle.

**Comment by DavidBruant** [comment]
Pour la référence, les *analytics* de gironde.fr semblent indiquer que sur la période août-septembre, le mobile constitue ~68% des visites

**Comment by thom4parisot** [comment]
[SVG to Canvas](http://www.svgopen.org/2010/papers/62-From_SVG_to_Canvas_and_Back/#svg_to_canvas) + [HTML Media Capture](https://w3c.github.io/mediacapture-fromelement/#html-media-element-media-capture-extensions) s'il faut générer du rendu vidéo des animations SVG — ah mais elles sont peut-être juste en HTML.

Bon, c'est une piste.

**Comment by DavidBruant** [comment]
Pour les stackchart, on peut voir le travail ici sur le responsive ici : https://github.com/dtc-innovation/dataviz-finances-gironde/pull/315

**Comment by DavidBruant** [comment]
Concernant l'animation, je vais essayer la technique suivante : 
* Sur desktop
    * animation avec un bouton "play" (plutôt que de se lancer seule comme actuellement)
    * définition qui apparaissent au fur et à mesure
* sur mobile
    * faire une vraie video (au sens élément HTML &lt;video>) avec les éléments sans les définitions
    * mettre les définitions de manière permanente sous la vidéo

Il y a de fortes chances qu'une vraie vidéo soit assez facile à produire à partir de l'animation actuelle. En utilisant un vrai élément &lt;vidéo>, on a déjà tout un tas de comportement built-in (fullscreen, rotation paysage/portrait) et ça économise le travail d'avoir à se battre contre des pixels ou le DOM/JS de gironde.fr
