### ISSUE TITLE
Bug d'affichage histogramme sur la page Dépenses Fonctionnement 2016

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#197]
Sur la page "dépenses de fonctionnement", la totalité des histogrammes n'est pas visible à cause d'un bug d'affichage

![capture d ecran 2017-07-03 a 2 27 33 pm](https://user-images.githubusercontent.com/23077793/27833471-5193c5b0-60d3-11e7-8f9c-e44a01d494de.png)

**Comment by DavidBruant** [comment]
Bien vu.
Le bug ici est due au fait que DF-1 et DF-2 sont deux présentations différentes d'un même total (par prestation ou par public). Il faut que les deux apparaissent dans le découpage en-dessous, mais dans ce graphique, il faudrait qu'ils n'apparaissent qu'une seule fois sous le nom "solidarités".

**Comment by DavidBruant** [comment]
Fait dans #203
