### ISSUE TITLE
exploration des recettes de fonctionnement : RF-862

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#202]
vérifier s'il est bien normal que la valeur soit à zéro et aucun article de la M52 en regard

**Comment by DavidBruant** [comment]
@akakeronos RF-862 n'est pas un identifiant connu. S'agit-il d'une typo ?
L'issue est-elle toujours pertinente ?

**Comment by akakeronos** [comment]
@DavidBruant ce n'est pas moi qui ait déposé cette issue

**Comment by DavidBruant** [comment]
Cette issue a été initialement créée par le compte github @datalocale (je ne sais pas pourquoi depuis récemment il s'affiche en "ghost" sur les issues créées il y a un moment). 
Je ne sais pas qui a créé cette issue si ce n'est pas toi ?

Je ferme cette issue si personne ne sait expliquer quel est le problème. Recréer une issue si le problème revient.

**Comment by thom4parisot** [comment]
J'aurais tendance à imaginer que @datalocale était un compte utilisateur qui a été transformé en organisation.

**Comment by akakeronos** [comment]
oui c'est ça. J'ai fait cela pour préparer le transfert du code source sur le dépôt de source de cette nouvelle organisation
