### ISSUE TITLE
[Animation construction budget] Mettre à jour les noms et montants des blocs

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#204]
Pour la mise à jour des blocs constitutifs de l'animation construction budget:  voici les noms validés pour chaque blocs ainsi que les formules et les montants associés. 
Ces données ont été validé par la DFI du département par mail le 06.07.17

**RECETTES DE FONCTIONNEMENT : 1 527 Millions d’€ (RF)**

-   DOTATION DE L’ÉTAT 219 Millions d’€ (RF5 )
-   FISCALITÉ DIRECTE (Taxe sur les propriétés bâties) 502 Millions d’€ (RF1)
-   FISCALITÉ INDIRECTE (DMTO) 619 Millions d’€ (RF2+RF3+RF4)
-   RECETTES DIVERSES 187 Millions d’€ (RF6+RF7+RF8+RF9)

**DÉPENSES DE FONCTIONNEMENT : 1376 Millions d’€**

-  SOLIDARITÉS : 844 Millions d’€  (DF1 ou DF2 normalement)
-  INTERVENTIONS (Subventions, Transports, SDIS…) 218 Millions d’€ (tous les DF3)
-  AUTRES (Personnel …) 314 Millions d’€ (DF4+DF5+DF6+DF7) 

**RECETTES D’INVESTISSEMENTS : 260 Millions d’€**

-   RECETTES D'INVESTISSEMENT : 45 Millions d’€ (RI)
-   EMPRUNT : 63 Millions d’€ (EM1+ EM2)
-   ÉPARGNE : 152 Millions d’€ (RF-DF) (arrondi supérieur)

**DÉPENSES D’INVESTISSEMENTS : 245 Millions d’€**

-  REMBOURSEMENT EMPRUNT 55 Millions d’€ (en dur)
-  ROUTES + COLLÈGES + BÂTIMENTS + AMÉNAGEMENT 123 Millions d’€
-  SUBVENTIONS (Communes … ) 67 Millions d’€

**Comment by DavidBruant** [comment]
Oki parf. Juste pour être transparent sur ce qui va avoir lieu, je ne mettrai à jour que les noms et les formules. Il faudra gérer les conflits sur les montants s'il y en a
