### ISSUE TITLE
Coordonner les codes couleurs des graphiques

### ISSUE THREAD

**Issue by SuzData** [datalocale/dataviz-finances-gironde#218]
Faire correspondre les couleurs par publics cités entre pages 
Focus Solidarités : https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/focus/SOLIDARITES
et page 
Explorer "Action sociales par publics" : https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-2

**Comment by DavidBruant** [comment]
Cette issue a été faite. Voir #243
