### ISSUE TITLE
Permettre le markdown dans les focus

### ISSUE THREAD

**Issue by SuzData** [datalocale/dataviz-finances-gironde#223]
Dans le Focus Solidarités, catégorie du détail des prestas "personnes âgées", insérer le lien dans la phrase :
"Elle peut être versée soit directement à la personne soit à l’établissement en charge de la personne, selon des critères d'attribution précis. "
lien : https://www.service-public.fr/particuliers/vosdroits/F10009
insérer sous "critère d'attribution précis

**Comment by thom4parisot** [comment]
Si ça peut aider, https://npmjs.com/markdown-it est le module le plus "standard" et personnalisable pour rendre le markdown à l'écran.

**Comment by DavidBruant** [comment]
@oncletom https://github.com/dtc-innovation/dataviz-finances-gironde/blob/fef6b7867ced5b906ccc85e438d99f747724512a/package.json#L64 ;-)

**Comment by DavidBruant** [comment]
oooooh ! tellement fat le snippet ! C'est nouveau, non ?

**Comment by thom4parisot** [comment]
@DavidBruant première fois que je le vois ! 💯  Bonne curation de modules ;-)

Mais du coup le rendu en markdown est fait ou pas encore ?

**Comment by thom4parisot** [comment]
> https://github.com/blog/2415-introducing-embedded-code-snippets

**Comment by oncletom** [comment]
> https://github.com/blog/2415-introducing-embedded-code-snippets

**Comment by DavidBruant** [comment]
> Mais du coup le rendu en markdown est fait ou pas encore ?

Oui pour les pages élément financiers, mais pas pour les focus (le besoin est apparu récemment)
