### ISSUE TITLE
Page présence sur le territoire

### ISSUE THREAD

**Issue by vinber** [datalocale/dataviz-finances-gironde#224]
# Présence sur le territoire

À travers ses missions, le département est le deuxième employeur de Gironde ????

## Dépenses de fonctionnement, en particulier frais de personnel (DF-4) et charges courantes (DF-6)

évolution maitrisée des dépenses de personnels et de gestion

2 graphes correspondant

et tout cela en étant présent sur l'ensemble du territoire à travers plusieurs centaines et sites, de métiers ... et malgré une augmentation de la démographie galopante.

## Carte sur la présence territoriale

- Une carte sur la présence territoriale avec le nombre d'agents rattachés à chaque batiment (données extraites d'Abila ?)

- iframe

iframe width="700" height="400" src="https://www.datalocale.fr/dataset/liste-des-batiments-du-conseil-general/resource/493edee8-a2f6-48c7-a61a-c865a5a499a8/view/6f064ce2-e618-4abd-a3d6-f3464f2d9f12" frameBorder="0"

**Comment by DavidBruant** [comment]
Début d'implémentation : #330 

Doc de référence : https://docs.google.com/document/d/1QNJNJM_CALXq9GUKLGhTiO-b5psalHZlJeIc0ekyr0E/edit#
