### ISSUE TITLE
La démo ne fonctionne plus

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#230]
C'est à cause de code spécifique à gironde.fr. Il faut créer 3 environnements : 
* `DEVELOPMENT` pour dev (watch)
* `PRODUCTION` pour gironde.fr (build)
* `DEMO` pour la démo sur gh-pages

**Comment by DavidBruant** [comment]
Il faut aussi corriger le chemin de `$home-illustration-url` dans home.scss

**Comment by akakeronos** [comment]
Salut,
J'aurais besoin d'un accès à la démo. Au pire pour la réunion de mardi, au mieux au plus vite ?
C'est possible ?
Bonne journée
Pascal

**Comment by DavidBruant** [comment]
La démo fonctionne à nouveau 
https://dtc-innovation.github.io/dataviz-finances-gironde/public/

**Comment by akakeronos** [comment]
Merci
