### ISSUE TITLE
incohérence entre chiffres et représentation dans une section de navigation

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#234]
Dans la page d'exploration https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DI-EM-3 les histogrammes affichent 0€ alors que le détail des lignes M52 affichent des montants

**Comment by DavidBruant** [comment]
C'est un problème d'échelle. L'histogramme affiche `0.0M€`. Cette approximation est correcte (les valeurs sont bien inférieures à 100.000€), mais inutile et peut créer de la confusion en effet.

**Comment by DavidBruant** [comment]
Sera corrigé à l'occasion de #146. Je laisse ouvert dans l'intervalle

**Comment by datalocale** [comment]
je ne sais pas comment régler ce conflit mais la présentation en millions semble être l aplupart du temps la plus conforme aux pratiques métiers
