### ISSUE TITLE
erreur dans l'affichage du pourcentage dans une page d'exploration de l'agrégé

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#236]
En cliquant sur l'année 2014 de la page https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DI-1-5 le pourcentage d'évolution affiche une valeur incorrecte "+Infinity%". Pour l'année précédente la variable affiche "+NaN%"

**Comment by DavidBruant** [comment]
Cet affichage n'existe plus dans le design final
