### ISSUE TITLE
navigation dans l'agrégé : remarques personnelles

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#239]
Remarques personnelles
En naviguant dans les chiffres de l'agrégé j'ai envie de : 
- cliquer sur les blocs de couleur et actuellement ils ne sont pas actifs. Le comportement souhaité serait d'être dirigé vers le détail de la section sélectionnée
- disposer d'illustration dans l'affichage en ascenseur en bas pour mieux comprendre et avoir envie d'explorer
- lire le texte d'explication contextuel juste en dessous du titre "évolutions sur ces dernières années" alors qu'actuellement il est situé sous la légende  
- voir le détail des textes des sous-sections affichées dans le bas de la page car cette partie de la page est assez vide. De plus je ne comprends pas l'apport de la coloration en gris lors du survol.
- mieux visualiser que je peux naviguer dans le temps en cliquant sur l'année. Après l'avoir fait si je ne suis pas attentif peu de choses changent à part le titre et le graphique du haut
- mieux comprendre le graphique grâce à une animation qui explique mieux le ratio de la section consultée par rapport à celle à laquelle elle est rattachée
- en fin de navigation, si je suis intéressé par les chiffres de la M52 je voudrais pouvoir chercher à l'intérieur, trier par type ou montant, avoir un affichage plus lisible

**Comment by DavidBruant** [comment]
J'ai du mal à savoir quoi faire de cette issue. Certains morceaux sont faits, d'autres pas. Certains morceaux sont dans d'autres issues d'autres n'ont jamais été discutés collectivement.

Je ferme cette issue. Réouvrir différentes issues avec les points spécifique, de préférence après discussion avec tout le monde.
