### ISSUE TITLE
Question de proportions sur les grandes masses budgédaires

### ISSUE THREAD

**Issue by thom4parisot** [datalocale/dataviz-finances-gironde#247]
@noeems faisait remarquer que c'était étrange de voir des masses budgétaires ont une taille identique alors que leur montant est différent.

1527 millions de de recettes de fonctionnement === 1376 millions de dépenses de fonctionnement ?

![different-figures-same-height](https://user-images.githubusercontent.com/138627/30523223-cdf81b3e-9bdd-11e7-9750-e91ad720dc37.png)

**Comment by DavidBruant** [comment]
(Vous regardez sur quel navigateur ? le nombre est sensé être en haut)

Ouais, le problème, c'est que si on gardait la proportionnalité, le texte du "107 millions" serait écrasé ou dépasserait.

Dur de ne pas lâcher quelque chose, alors on a pris le parti de casser la proportionnalité (`min-height`) au nom de l'esthétisme. Par contre, ça transmet tout le même l'information que le fonctionnement est beaucoup plus gros que l'investissement.

**Comment by thom4parisot** [comment]
Sur Chrome.

Oui je vois le dilemme.

Faire `min-value = 30px` et `max-value = 300px` pour faire un truc qui retourne la bonne échelle de pixels en fonction d'un montant, ça serait pertinent ?

Chuis dac que le montant véhicule la bonne information. @noeems était perturbée par le fait que ça avait la même taille ("qu'est-ce que je suis censée lire ?").

Alors que de mon côté, je n'avais pas regardé les montants, juste le `1,63 et 1,62` et fais le raccourci que recettes {fonctionnement, investissement} = dépenses {fonctionnement, investissement}. 🤓

**Comment by DavidBruant** [comment]
> Faire min-value = 30px et max-value = 300px pour faire un truc qui retourne la bonne échelle de pixels en fonction d'un montant, ça serait pertinent ?

Je ne comprends pas cette idée. Je suis preneur d'une PR ou on en papote quand on se voit.
Mais en gros, on ne peut pas imposer un triplet {min, max, proportionnalité} dans le cas général. Faut toujours choisir d'en dropper un. 
Là, on a drop la proportionnalité. Dans les pages élément financier, on a droppé le min.
Dropper le max mènerait à des situations absurdes, donc on ne l'a même pas considéré :-p

**Comment by thom4parisot** [comment]
<img width="1144" alt="screen shot 2017-09-19 at 15 48 50" src="https://user-images.githubusercontent.com/138627/30595659-17493c44-9d52-11e7-9dd7-9c0bfa2acbbe.png">

**Comment by noeems** [comment]
She's a beauty! And by that I mean this screen, but also the entire project.
Bravo, ladies & gents.

**Comment by DavidBruant** [comment]
> She's a beauty! And by that I mean this screen, but also the entire project.
> Bravo, ladies & gents.

ho, j'avais pas vu ce commentaire 😊 merci @noeems :-)

**Comment by DavidBruant** [comment]
De mémoire après discussion, nous avions conclu que le problème n'avait pas de solution simple et que la solution actuelle est convenable, même si imparfaite.

Je ferme l'issue. La réouvrir ou en réouvrir une autre si j'ai mal retenu la discussion sur le sujet
