### ISSUE TITLE
texte tronqué sur une section de la page focus solidarité

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#248]
Le texte descriptif de la sous-section personne handicapé semble tronqué
"Trois types d’aides ont été allouées aux personnes handicapées par le Département en 2016 : - La PCH (Prestation de Compensation du Handicap), a été versée à 9 975 personnes bénéficiaires - La prestation d’hébergement a financé 2763 places d'hébergement - L'ACTP (Allocation de Compensation pour Tiers Personne) a financé l'emploi d'aides à domicile pour 1 128 personnes (All"

**Comment by DavidBruant** [comment]
Je crois que ce texte n'existe plus ?
