### ISSUE TITLE
décalage du texte de définition

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#253]
Sur la page https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-6-1-2 le texte de définition semble décalé

**Comment by DavidBruant** [comment]
En effet.
Note pour moi-même : `flex: 1;` sur le premier enfant peut résoudre le problème

**Comment by DavidBruant** [comment]
Cette issue n'a plus de sens depuis que l'on est passé du camembert aux barres
