### ISSUE TITLE
propositions d'évolution de l'animation construction du budget

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#254]
Je propose comme règle générale que les blocs de texte s'affichent en même temps que débute chaque section d'animation et que la prochaine animation ne débute pas avant un temps minimal de lecture
* Affichage pendant l'arrivée du bloc recette de fonctionnement 
Pour construire son budget le Département dispose de plusieurs sources de revenus ou recettes de fonctionnement. Ces recettes proviennent principalement du produit des impôts et taxes directes et indirectes, ainsi que des dotations dont le montant est fixé par l'État et sont exclusivement réservées au paiement de dépenses de fonctionnement
* Affichage pendant l'arrivée du bloc dépenses de fonctionnement
Ces recettes financent les allocations et prestations sociales ou de solidarité gérées par le Départment, les services de secours (pompiers), les transports, les collèges, les routes et les intérêts d’emprunts. 
Pour assurer ces missions sur l'ensemble du territoire il dépense pour disposer des ressources humaines et des moyens de son fonctionnement.
* Affichage pendant le passage des non-dépenses vers les recettes d'investissement
En contrôlant ses dépenses de fonctionnement propre le Département économise et épargne pour financer les infrastructures et services de proximité sur le territoire.
* Affichage pendant l'arrivée des recettes d'investissement
Les recettes d'investissement sont principalement constituées de dotations de l’Etat et de subventions. Elles peuvent également provenir de vente de patrimoine.
* Affichage pendant l'arrivée des emprunts
Les emprunts permettent au Département d'atteindre l’équilibre budgétaire et d’investir dans des projets d’ampleur ou durables.
* Affichage pendant le passage des dépenses d'investissement
Les dépenses d'investissement concernent des programmes structurants ou stratégiques pour le développement du territoire girondin : bâtiments, routes, collèges, etc.
* Affichage à la fin de l'animation
Chaque année le compte administratif du Département doit être en équilibre comme l'en oblige la loi. La qualité de sa gestion financière permet de garantir l'exercice de ses missions sur le territoire et sa capacité d'investir en faveur de son développement

**Comment by akakeronos** [comment]
David, est-ce que l'intégration des définitions dans l'animation est bien prévue dans la sortie publique du 9 novembre ?

**Comment by DavidBruant** [comment]
> David, est-ce que l'intégration des définitions dans l'animation est bien prévue dans la sortie publique du 9 novembre ?

Sauf information contraire de ma part, tout ce qui est dans la [milestone correspondant à la sortie du 9 novembre](https://github.com/dtc-innovation/dataviz-finances-gironde/milestone/5) est prévu dans la sortie publique du 9 novembre. Tout ce qui n'est pas dans cette milestone n'aura pas lieu d'ici le 9 novembre.

La composition de cette milestone est liée à la réunion de priorisation du 17 octobre. J'ajoute aussi automatiquement tout ce qu'il y a à faire en terme de déploiement, car c'est évidemment bloquant pour la sortie.
Par défaut, toute autre nouvelle issue est prévue pour après le 9 novembre, sauf indication contraire provenant d'un consensus DSIN + DFI + DirCom (comme les 4 barres par exemple).

Cette issue est dans la bonne milestone. Elle est donc bien prévue pour le 9 novembre.
