### ISSUE TITLE
il manque un chiffre dans le paragraphe focus solidarité

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#255]
Dans le paragraphe en face du graphique 50% des dépenses on lit "Avec 120 000 prestations allouées et xxx millions d'euros mobilisés en 2016, les dépenses de Solidarités pour soutenir les personnes fragilisées évoluent de +4,31% par rapport à 2015."

**Comment by DavidBruant** [comment]
Corrigé à ma connaissance
