### ISSUE TITLE
intégration icônes gironde

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#257]
Les premières icônes servant à illustrer les pages focus ont été livrées
Elles sont disponibles sous licence MIT ici https://github.com/datalocale/pictoGironde

**Comment by DavidBruant** [comment]
Un début de travail sur l'intégration des icônes a été fait. A voir ce qu'il reste à faire.

**Comment by DavidBruant** [comment]
Les icônes ont été intégrées pour les pages focus solidarité et investissement

@akakeronos, y a-t-il des icônes pour le focus présence ?

**Comment by akakeronos** [comment]
Oui
https://github.com/datalocale/pictoGironde/blob/master/AgentesDepartement.svg :: https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DI-6-1-3
https://github.com/datalocale/pictoGironde/blob/master/Carburant.svg :: https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-6-1-1
https://github.com/datalocale/pictoGironde/blob/master/depensesElectricite.svg :: https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-6-1-2
