### ISSUE TITLE
présentation des chiffres

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#259]
Toujours présenter les chiffres en millions avec million abrégé sous la forme M d'€ y compris dans l'animation de la somme affichée à droite du camembert

**Comment by DavidBruant** [comment]
Ca rentre en conflit direct avec #234 :-/

**Comment by DavidBruant** [comment]
Je reprends ici le commentaire qui a été écrit [ailleurs](https://github.com/dtc-innovation/dataviz-finances-gironde/issues/234#issuecomment-331446849)

> je ne sais pas comment régler ce conflit mais la présentation en millions semble être l aplupart du temps la plus conforme aux pratiques métiers

Je suis surpris que le métier se satisfasse d'écrire "0.0M€" pour les sommes inférieurs à 100.000.
De mémoire, notre contact DFI nous avait dit que pour les sommes inférieures à 100.000€, ils écrivaient  la somme telle quelle.
