### ISSUE TITLE
explication de la différence entre le montant des recettes et des dépenses

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#261]
Suite au retour de M.Rouveyre il faut trouver un moyen d'expliquer pourquoi on a 1,62 d'un côté et 1,63 de l'autre
Il faudrait ajouter ce texte sous le graphique des 4 blocs

Les chiffres étant issus du compte administratif, la différence entre le montant des recettes et le montant des dépenses représente l'excédent de l'exercice.

**Comment by DavidBruant** [comment]
Corrigé à l'occasion de #267
