### ISSUE TITLE
harmoniser l'ordre de présentation des éléments des sections de navigation

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#264]
Essayer de trouver un moyen de présenter dans le même ordre : 
* les blocs de l'histogramme
* les éléments de la légende
* les blocs du graphique du bas de page

Par exemple sur la page https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF

On a le bleu en bas dans l'histogramme donc on laisse le bleu en bas de la légende et on place le bloc bleu du graphique en bas de la page en bas de la page :)

**Comment by DavidBruant** [comment]
Pour référence, l'idée ici était que le sens de lecture est différent. Dans un diagrammes avec des barres superposées, on va préférer avoir les gros montants "en bas" donc un ordre décroissant en partant par le bas.

Par contre, dans le sens de lecture normal, on va préférer avoir les plus gros éléments d'abord, donc en haut.
