### ISSUE TITLE
Trouver un bon hébergement pour les icones du CD33

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#278]
[Github n'est pas un hébergeur](https://help.github.com/articles/what-is-github-pages/#usage-limits). Il faut trouver un autre endroit d'où récupérer les icônes.

**Comment by DavidBruant** [comment]
J'ai utilisé rawgit.com pour le moment

**Comment by akakeronos** [comment]
à héberger sur gironde.fr en tant que média

**Comment by DavidBruant** [comment]
C'est désormais hébergé par gironde.fr en tant que média
