### ISSUE TITLE
S'assurer que le formatage unifié des sommes convient à tout le monde

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#282]
Suite à #281

**Comment by datalocale** [comment]
en tant que Laurence je souhaite que la syntaxe de formatage des sommes supprime le d' ou le D' devant le symbole €

Edit de @DavidBruant : suppression du nom de famille

**Comment by DavidBruant** [comment]
Après discussions, il semblerait qu'il y ai eu une mauvaise communication des attentes dans #259.
La correction est dans #297
