### ISSUE TITLE
build pour démo demain

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#285]
Salut David,

Je viens de récupérer les modifications que tu as effectuées depuis vendredi après-midi en vue de regénérer un build pour l'intégrer au site de préprod demain en effectuant un 
git pull dtc master
ensuite j'ai voulu faire un npm run build:gironde:public.fr
mais j'obtiens une erreur 

npm run build:public:gironde.fr
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build:public:gironde.fr"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! missing script: build:public:gironde.fr
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pascal romain\AppData\Roaming\npm-cache\_logs\2017-09-24T1
7_17_23_408Z-debug.log

Est-ce que j'ai raté quelque chose ?

**Comment by datalocale** [comment]
[2017-09-24T17_17_23_408Z-debug.log](https://github.com/dtc-innovation/dataviz-finances-gironde/files/1327500/2017-09-24T17_17_23_408Z-debug.log)

**Comment by DavidBruant** [comment]
Désolé, j'ai changé la commande. 
Il s'agit de `npm run build-gironde-fr:public`

**Comment by datalocale** [comment]
Ok merci

**Comment by datalocale** [comment]
ça génère un nouveau css mais pas de bundle.js. C'est normal ?

**Comment by datalocale** [comment]
ah non pardon j'ai mal vu. C'est bon
