### ISSUE TITLE
affichage des icônes sur les pages focus

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#289]
En fonction de la résolution ou de la taille d'affichage de l'écran les images en svg ne s'affichent pas correctement sur les pages focus

**Comment by DavidBruant** [comment]
J'aurais besoin de screenshots et de plus de détails sur les configurations qui posent problème

**Comment by akakeronos** [comment]
Je ne reproduis ce problème qu'avec Chrome
Avec IE je n'arrive pas à afficher la page malgré le changement de paramètre de sécurité qui permet d'afficher les autres pages.
peso j'utilise Chrome version 64.0.3241.3 (Build officiel) canary SyzyASan (32 bits)
![iconefocussolidarite](https://user-images.githubusercontent.com/10322028/31658975-e5927a52-b332-11e7-8fcd-20b85b7591c0.PNG)
