### ISSUE TITLE
Déployer sur gh-pages avec Travis

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#29]
Priorité assez haute puisque permet de mettre dans les mains de plus de gens et d'avoir des retours.

**Comment by DavidBruant** [comment]
Le taf est prémaché par : 
* https://github.com/DavidBruant/autour-de-moi/blob/master/.travis.yml
* https://github.com/DavidBruant/autour-de-moi/blob/master/tools/deploy.sh

**Comment by DavidBruant** [comment]
Na, gros échec pour l'instant.
https://travis-ci.org/dtc-innovation/dataviz-finances-gironde
Pas compris pourquoi il leak mon token non plus :-/

**Comment by DavidBruant** [comment]
Ah nan cool, c'est bon, ça marche. Sur https://davidbruant.github.io/dataviz-finances-gironde/ pour le moment

**Comment by DavidBruant** [comment]
Success! 
https://dtc-innovation.github.io/dataviz-finances-gironde/

**Comment by vinber** [comment]
Cool :)
