### ISSUE TITLE
affichage de l'icône bonhomme.svg sur la page focus solidarité

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#290]
Dans l'intégration pré-prod l'icône bonhomme.svg https://dtc-innovation.github.io/dataviz-finances-gironde/images/bonhomme.svg ne s'affiche pas

**Comment by DavidBruant** [comment]
J'imagine que c'est qu'il n'est pas importé en tant que média dans le CMS comme on a fait avec l'image de la home

**Comment by DavidBruant** [comment]
Cette issue est-elle toujours d'actualité ?

**Comment by DavidBruant** [comment]
Il s'agit d'un problème de déploiement, pas de code à corriger ici
