### ISSUE TITLE
Le premier clic vers une page d'un élément financier fait subir une longue attente

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#291]
~4s sur mon ordinateur
~10s sur mon téléphone

Il s'agit de calculs purs (pas de latence réseau, pas de timeout, etc.). 
Après analyse avec le profiler, ces calculs correspondent au calcul de l'arbre agrégé (et donc les calculs des règles de filtre) sur les 5 comptes administratifs.
Chaque filtre passe toutes les lignes d'un CA et la teste. Si on dit qu'un CA, ça fait ~1200 lignes, on aboutit à 480000 appels de fonctions (5 CA x 1200 lignes par CA x 80 règles par ligne) qui ne sont pas très grosses individuellement, mais ça commence à faire (surtout que certaines règles en appellent d'autres, donc il est possible que le 80 soit plutôt 100 (600000)).

La fonction est mémoizée, donc on ne subit ce coût qu'une seule fois.

Plusieurs pistes de solution possibles (de la plus simple à la plus compliquée) : 
1. effectuer le calcul quand on reçoit les données. Le chargement initial va donner une impression de *lagger* un peu et petits à-coups sur le scroll pendant les ~10 premières secondes, mais après tout sera instantané
2. optimiser les calculs. Vu qu'on a une partition, une fois qu'une ligne est dans une règle, elle n'a pas besoin d'être testée contre les autres règles. Le gain de cet idée n'est pas clair. On réduirait peut-être le temps de calcul de 50%. Mais il faut que les formules forment une vraie partition.
3. Faire le fetch, le parsing et le calcul dans un WebWorker (IE10+) puis envoyer les données calculées à la page. C'est un transfert de ~5-10Mo via un postMessage. Ca risque de créer une petite pause de 2-3 secs (desktop), 4-5secs sur mobile, mais le ressenti sur le chargement initial sera meilleur.
4. Pré-calculer les données côté serveur (parce qu'en vrai, y'a pas besoin de recalculer les règles côté client à chaque fois)

**Comment by thom4parisot** [comment]
> 1. effectuer le calcul quand on reçoit les données.
> 3. Faire le fetch, le parsing et le calcul dans un WebWorker (IE10+) puis envoyer les données calculées à la page. C'est un transfert de ~5-10Mo via un postMessage.

Quand on arrive sur la page d'accueil ça va. Mais c'est moyen pratique quand on arrive sur une autre page, ou lorsqu'une page est rafraichie. C'est aussi compter sur une bonne bande-passante.

> 4. Pré-calculer les données côté serveur (parce qu'en vrai, y'a pas besoin de recalculer les règles côté client à chaque fois)

Ça me parait être le gain le plus notable, à la fois en terme de bande-passante et de CPU.

T'en penses quoi ?

**Comment by DavidBruant** [comment]
La solution 1 m'est triviale à implémenter (ajout d'un appel de fonction).

Je suis d'accord que la 4 est la bonne à long terme, mais va prendre plus de temps à faire.

> C'est aussi compter sur une bonne bande-passante.

Je n'ai pas compris ce morceau. Actuellement sur gh-pages, 3Mo sont transférés découpés comme ça : 
- 1,8M : illustration de la home
- 750k : JavaScript
- 160k : données financières
- 50k : css
- 20k : données textuelles

Sur les 160k des données financières, on peut ptèt en gratter 60, mais sur 3Mo ou même comparé au 750k du JS, je ne suis pas sûr que ça vaille le coup.

Le problème de ce bug est purement un problème de calcul

Si cette issue est priorisée, je ferai la solution 1 et on verra ce que ça change.
La solution 4 deviendra impérative si on passe par les fichiers XML, ça peut attendre ce moment-là.

**Comment by DavidBruant** [comment]
Pour info anecdotique, peu de gens font remonter qu'il y a ce problème de perf. En dépit de ce que nous raconte la Silicon Valley avec ses "100% d'utilisateurs s'en vont après 10sec d'attente", mon expérience, c'est que les gens sont assez tolérants à l'attente. Ptèt qu'on n'a pas tous leur qualité de fibre/4G.

**Comment by DavidBruant** [comment]
La proposition 1 est un XS
