### ISSUE TITLE
rendre disponible les lignes de la M52 dans le contexte de l'exploration M52

### ISSUE THREAD

**Issue by datalocale** [datalocale/dataviz-finances-gironde#294]
Dans le cadre de l'exploration de la M52 je souhaiterais que le détail des lignes de la M52 liées à l'arbre de navigation soient affichées comme dans l'exploration agrégée.

**Comment by DavidBruant** [comment]
Je ne comprends pas cette issue
Par exemple, si je regarde https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/M52-DF-R021 je vois les lignes de la M52 en bas de page
