### ISSUE TITLE
TODO finances après atelier 3/10

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#296]
Prise de note brute, à redécouper et à discuter en plus grand nombre : 

```
Assistantes maternelles devraient être dans la social, pas dans les frais de personnel
=> Laurence va vérifier. Peut-être qu'il faudrait hardcoder ce déplacement pour 2012-2016

=> Dans l'animation, trouver d'où vient le nombre de la solidarité (796M€)
=> copier les labels M52 de http://odm-budgetaire.org/composants/normes/2017/M52/M52/planDeCompte.xml
=> Un texte qui annonce M52 + Différence "fonction" et "agrégation par nature"
=> Focus invest : investissement = DF-1 + DF-2 (hors emprunt)
+ Virer la brique rouge du stackchart (remboursement emprunt)
+ dans les textes/titres expliciter "hors remboursement emprunt"
=> https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/RF-8 
RF-8-2 est systématiquement à 0 (formule qui sera sur 2017, mais n'existait pas avant)
=> animation : mettre des min-height
=> Revisualiser DF-1 & DF-2 : changer la légende pour qu'elle aie 2 liens
Dans la partition en fin de page, écrire une définition unique pour DF-1 et DF-2 qui invite à naviguer vers les 2
```

**Comment by akakeronos** [comment]
Pour partager également mes notes prises à l'issue de cette journée, j'ai noté que Berengère trouvait le rendu graphique "pas abouti" voire "pas beau". Il me semble que cela nous autorise à faire des propositions d'amélioration graphique. Je propose notamment de revoir l'utilisation des niveaux de titres de la feuille de style de Gironde.fr, de revoir la charte graphique des boutons en savoir plus.
En complément des réflexions actuelles concernant l'amélioration du camembert de contextualisation, je me demande s'il ne suffirait pas d'en réduire la taille car son côté un peu imposant lui donne peut-être une place d'attention trop importante.
Je propose également de tester la suppression de la présentation graphique des détails financiers du bas de la page qui semble redondant et n'apporte pas d'informations suffisamment complémentaires pour justifier sa présence.
Pour la proposition visant à transformer l'animation de la construction du budget en film d'animation, comment procède-t-on ?
Pour discussion

**Comment by DavidBruant** [comment]
> Dans l'animation, trouver d'où vient le nombre de la solidarité (796M€)

a été corrigé dans #304

**Comment by DavidBruant** [comment]
Différentes issues ont été créées pour les différents points
