### ISSUE TITLE
Vérifier les questions d'entiers en JS

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#3]
On commence à manipuler des milliards et des données financières. Vérifier que JS peut gérer avec précision sur des entiers de cette taille.

**Comment by thom4parisot** [comment]
Sinon : https://www.npmjs.com/package/big-integer

**Comment by DavidBruant** [comment]
Yes. Pour l'instant, Même sur des grosses sommes, j'ai vu JavaScript et LibreOffice être d'accord (modulo les problèmes d'arondis, mais qui n'affectent que les 10-12ème décimales).
Je ferme. On revisite si on découvre un problème.

Pour l'affichage, `.toFixed(2)` sera notre [meilleure amie](https://www.youtube.com/watch?v=Hyfje_Jen-w)
