### ISSUE TITLE
décalage sur la page focus investissement

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#300]
Sur mon écran les 2 pages focus ne s'affichent pas de manière identique. 
La page investissement génère l'apparition d'un ascenseur horizontal
![decalagepagefocusinvestissement](https://user-images.githubusercontent.com/10322028/31164057-b4f5b906-a8e5-11e7-93be-91dcb322bb9c.PNG)

**Comment by DavidBruant** [comment]
Ce genre de problème m'inspire qu'il va falloir faire une sortie publique sur un URL cachée assez rapidement pour voir ce que ça donne en conditions réelles (genre vraiment réelles, pas preprod), notamment pour toutes les questions de responsive et usage sur mobile.

**Comment by DavidBruant** [comment]
Je n'observe pas ce problème sur la prod. Est-il toujours d'actualité ?

**Comment by DavidBruant** [comment]
Pas de nouvelles, bonnes nouvelles
