### ISSUE TITLE
Crash with Chrome

### ISSUE THREAD

**Issue by samgoeta** [datalocale/dataviz-finances-gironde#302]
https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/focus/PRESENCE crashes my Chrome browser, I had to close and restart my browser

**Comment by samgoeta** [comment]
Tested on Mac0S 10.12.6

**Comment by thom4parisot** [comment]
Salut @samgoeta ; si c'est le même problème que j'avais rencontré, ça serait à #114 et au fait que les contenus associés à cette page n'existent pas.

Peut-être que @datalocale ou @DavidBruant ont une idée quant à la production des contenus.

**Comment by DavidBruant** [comment]
Merci pour le report de bug @samgoeta !

@oncletom yes, c'est le même bug
Il disparaitra quand on fera vraiment la page en effet. 

Pour autant, je vais faire le choix de garder l'issue ouverte avec le [bon commit](https://github.com/dtc-innovation/dataviz-finances-gironde/tree/5b063c7a079ceb1231f85c7407a8e4f0f8032a7e) pour reporter le bug chez Chrome quand l'activité autour de ce repo sera plus calme, parce que ce n'est pas normal que Chrome crash. Depuis #114, le crash existe encore, donc c'est un vrai bug, donc ils voudront le savoir (mais il faudrait écrire un test case plus réduit que l'état actuel du repo pour qu'ils puissent enquêter plus facilement).

**Comment by DavidBruant** [comment]
Le bug est désormais corrigé
