### ISSUE TITLE
Réduction budgétaire de pixels sur la home en mobile + Chromium (et dérivés)

### ISSUE THREAD

**Issue by thom4parisot** [datalocale/dataviz-finances-gironde#305]
Constaté sur Android avec Chrome et Brave.

![screenshot_20171016-152156](https://user-images.githubusercontent.com/138627/31614565-131dfafc-b287-11e7-824d-6a1fbe3b7df6.png)

**Comment by DavidBruant** [comment]
Je confirme.
Je le corrigerai à l'occasion de #196

**Comment by thom4parisot** [comment]
Curieusement le contenu ne génère pas de hauteur. Ajouter un `min-height` fait le taf' mais ça me semblerait être une rustine un peu bancale. Je ne comprends pas trop d'où ça vient pour l'instant :-(

<img width="754" alt="screen shot 2017-10-20 at 17 07 56" src="https://user-images.githubusercontent.com/138627/31830871-6d95216a-b5b9-11e7-874c-0171d435a77a.png">

PS : donc oui ça le fait aussi sous Chrome desktop, simplement en redimensionnant la fenêtre.

**Comment by DavidBruant** [comment]
Je suppose que les enfants flex ne se voient pas attribuer de hauteur.
En mettant `display:block`, ça roule. J'ai corrigé comme ça (prochaine PR qui viendra cette aprèm)
