### ISSUE TITLE
Utiliser les bons liens pour les ressources sur la preprod et la prod

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#313]
Pour la préprod voilà comment se présente le code dans le bloc html5
<div class="cd33-finance-dataviz"></div>
<script src="/media/1938/field_dataviz_files/7"></script>
<script src="/media/1938/field_dataviz_files/5"></script>
<link rel="stylesheet" href="/media/1938/field_dataviz_files/6" type="text/css">

La page media associé fournit ces différents liens qui ne changeront plus dans le contexte de la preprod

/media/1938/field_dataviz_image/0 l'image de la home

/media/1938/field_dataviz_files/0     cedi_2016_CA.csv  
/media/1938/field_dataviz_files/1      cedi_2015_CA.csv  
/media/1938/field_dataviz_files/2      cedi_2014_CA.csv
/media/1938/field_dataviz_files/3      cedi_2013_CA.csv
/media/1938/field_dataviz_files/4      cedi_2012_CA.csv
/media/1938/field_dataviz_files/5      dataviz-finance-gironde-fr-bundle.script
/media/1938/field_dataviz_files/6      public.css
/media/1938/field_dataviz_files/7      polyfill.script
/media/1938/field_dataviz_files/8 	Insertion.svg 		
/media/1938/field_dataviz_files/9 	Colleges.svg 		
/media/1938/field_dataviz_files/10 	Enfance.svg 		
/media/1938/field_dataviz_files/11 	EnvironnementAmenagement.svg 		
/media/1938/field_dataviz_files/12 	Handicapes.svg 		
/media/1938/field_dataviz_files/13 	Patrimoine.svg 		
/media/1938/field_dataviz_files/14 	routes.svg 		
/media/1938/field_dataviz_files/15 	SoutienCommunes.svg 		
/media/1938/field_dataviz_files/16 	Personnesagees.svg 		
/media/1938/field_dataviz_files/17 	bonhomme.svg 		

/media/1938/field_dataviz_files/18    aggregated-atemporal.csv 
/media/1938/field_dataviz_files/19    aggregated-temporal.csv
/media/1938/field_dataviz_files/20    m52-fonctions-atemporal.csv

Pour le déploiement en prod il faudra recharger tous les médias une première fois et ensuite noter le numéro du média (ici 1938) et le reste sera inchangé

**Comment by DavidBruant** [comment]
As-tu chargé les fichiers de textes (atemporels/temporels) aussi ?

**Comment by akakeronos** [comment]
comme tu peux le voir toi même non je n'y avais pas pensé. Maintenant c'est fait
