### ISSUE TITLE
"Comprendre la construction d'un budget" se charge partiellement en desktop

### ISSUE THREAD

**Issue by thom4parisot** [datalocale/dataviz-finances-gironde#318]
Les entêtes de colonnes s'affichent bien mais aucune animation n'est lancée.

<img width="1552" alt="screen shot 2017-10-20 at 10 53 18" src="https://user-images.githubusercontent.com/138627/31815604-13f3c9c4-b585-11e7-8242-d72c749dff2f.png">

Avec une taille de fenêtre plus petite, l'affichage des colonnes est correct (encore que je ne puisse pas jouer la vidéo)

<img width="599" alt="screen shot 2017-10-20 at 10 55 16" src="https://user-images.githubusercontent.com/138627/31815670-43c60ebe-b585-11e7-9d8a-b5a2ff9a435b.png">

Comportement constaté avec Chrome 62 et Firefox 55.

**Comment by DavidBruant** [comment]
> Les entêtes de colonnes s'affichent bien mais aucune animation n'est lancée.

Oui, il s'agit d'un changement demandé et implémenté récemment. 
Avant l'animation se lançait seule, sauf que c'était en-dessous du fold, donc l'utilisateur ne s'en rendait pas compte.
Est-ce que l'animation se lance quand tu cliques sur "jouer" ?

>  (encore que je ne puisse pas jouer la vidéo)

Je m'étais gouré dans le lien. Corrigé dans #317 normalement (dispo dans 10mins)

**Comment by thom4parisot** [comment]
Quand je clique c'est OK (la première fois que j'avais essayé, hier, ce n'était pas le cas).

Ça me gratte mais je vais dormir dessus pour savoir si c'est juste le changement ou autre chose.

**Comment by DavidBruant** [comment]
Ca me gratte aussi, mais je le garde en background pendant que j'avance sur d'autres sujets.

Faut ptèt mettre le bouton au milieu pour inciter à cliquer ou mettre un poster qui montre l'état de fin plutôt que l'état du début.

**Comment by thom4parisot** [comment]
Ceci est un état par défaut qui fait plus de sens (en tous cas, pour ma pomme) :

- rendre le bouton d'animation visible (en gris et en haut à droite d'une grande zone vide, je ne crois pas que l'affordance 
- afficher le contenu par défaut
- indiquer l'intention de l'animation dans le bouton (le wording n'est clairement pas le bon)

<img width="987" alt="screen shot 2017-10-20 at 17 27 21" src="https://user-images.githubusercontent.com/138627/31831640-12422e72-b5bc-11e7-8856-184c383f8a13.png">

**Comment by DavidBruant** [comment]
Corrigé par #378
