### ISSUE TITLE
Avoir deux pages déployées

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#32]
Le premier qui correspond plus ou moins à https://github.com/dtc-innovation/dataviz-finances-gironde/tree/d51f36a27512297db02faaca0e1f69a07ca959cf qui est un outil d'analyse d'une instruction M52.
Le second correspond plus à une dataviz avec éditorialisation.

**Comment by thom4parisot** [comment]
@DavidBruant tu penses quoi d'avoir _un seul_ déploiement mais deux pages html genre (`index.html` et `debug.html`) ?

Par la suite, j'imaginais aussi qu'on pourrait avoir une page HTML par instruction (`/2015`, `/2014` etc…). Va y avoir du contenu éditorialisé, potentiellement différent par année et y'a pas besoin de tout avoir dans une seule page HTML.

**Comment by DavidBruant** [comment]
Pardon, j'ai dit de la merde. Oui oui, un seul déploiement qui déploie 2 pages.

Je suis indécis sur le nombre de pages HTML à terme. On peut avoir une seule page et jouer avec History API + client-side router.

Mais pour le moment, 2 pages, ça fera bien le taf.

**Comment by thom4parisot** [comment]
👍

**Comment by DavidBruant** [comment]
Fait
