### ISSUE TITLE
Modifications focus investissement

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#322]
Extrait du compte-rendu du 17 octobre :
 
> il faut enlever le remboursement des emprunts du graphique et de la légende.
>
> Aussi, il est demandé à ce que les éléments du graphique soient découpés pour reprendre les 5 détails plus bas (et que le code couleur soit ajusté en fonction)
> 
> Les détails sont à afficher par ordre décroissant du montant (même si ça mélange les subventions et les équipements propres)

**Comment by akakeronos** [comment]
moi j'ai noté par ordre décroissant mais en gardant la logique des blocs équipements propres et subventions

**Comment by DavidBruant** [comment]
> ordre décroissant mais en gardant la logique des blocs équipements propres et subventions

Donc exactement [l'ordre d'aujourd'hui](https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/focus/INVEST) ?

**Comment by akakeronos** [comment]
Non le montant des dépenses de subventions aux communes est supérieur à celui des dépenses d'environnement et d'aménagement il doit donc se trouver avant celui ci.
Avec la clairifiication des couleurs cela devrait rendre l'ensemble plus lisible

**Comment by DavidBruant** [comment]
Remplacé par #341
