### ISSUE TITLE
retour compatibilité IE11

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#329]
1. J'arrive sur la page d'accueil, je clique sur explorer, je clique sur le rectangle orange DF sur la section grandes masses budgétaires, le focus de la page remonte vers le haut mais cette action ne me conduit pas sur la page finances-details
2. Je clique sur les autres liens de la section grandes masses budgétaires, rien ne se passe.
3. Je vais sur https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/explorer : j'ai le même comportement
4. En cliquant à plusieurs reprises je finis par arriver dans la navigation des comptes. Tout fonctionne correctement.
5. Je veux cliquer sur le fil d'ariane pour revenir à l'accueil, le bouton ne semble pas fonctionner
6. Le processeur de mon ordinateur monte à 30% pour IE.
7. je suis obligé de fermer mon navigateur

Il faut que je teste sur d'autres postes car le problème vient peut-être de mon ordinateur

**Comment by DavidBruant** [comment]
Merci pour le report de bug !

> Je clique sur les autres liens de la section grandes masses budgétaires, rien ne se passe.

Je soupçonne qu'il s'agisse de #291, mais il faudra que je vérifie.
