### ISSUE TITLE
Rajouter les corrections d'agrégation à la prod

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#333]
Un identifiant de ressource sera assigné (sûrement /media/XXXX/field_dataviz_files/21 ?)

**Comment by akakeronos** [comment]
je comprends qu'il faut que je dépose un fichier en plus corrections-agregation.csv ?

**Comment by akakeronos** [comment]
je confirme que l'id du fichier est bien 21
