### ISSUE TITLE
détail M52 sur DF-7

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#357]
Je ne sais pas si c'est normal mais il n'y a pas de détail chiffré sur cette feuille https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-7

**Comment by DavidBruant** [comment]
Il s'agit désormais de https://www.gironde.fr/un-budget-au-service-des-solidarites-humaine-et-territoriale#!/finance-details/DF.7
et c'est corrigé
