### ISSUE TITLE
RF-8-2 affiche 0€

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#360]
Pour mémoire à vérifier du côté des données s'il y a un souci https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/RF-8-2

**Comment by DavidBruant** [comment]
Il s'agit d'une "singularité" déjà constatée par Laurence. En fait, il n'y a pas de données pour RF-8-2 entre 2012 et 2016, mais il y en aura en 2017.
En en discutant informellement, nous avions convenu que ce n'était pas très grave.

Nous pouvons formaliser cette décision. 
Une manière de pallier à l'étrangeté de la page RF-8-2 peut être de mettre un texte temporel qui explique qu'il y aura des données pour le CA 2017.

**Comment by DavidBruant** [comment]
Non-discuté le 6 novembre. Attendra après le 9.

**Comment by DavidBruant** [comment]
Le service finance est autonome sur ces sujets-là désormais
