### ISSUE TITLE
titres section M52

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#361]
Sur la page explorer les titres des légendes des sections de la M52 ne font apparemment pas appel au fichier des définitions. Je vais donc les modifier directement dans la page.
De plus ces légendes utilisent également une taille de police de 1.2em alors qu'il vaudrait mieux uniformiser avec la taille des paragraphes en 1em

**Comment by DavidBruant** [comment]
> Sur la page explorer les titres des légendes des sections de la M52 ne font apparemment pas appel au fichier des définitions

Lequel ?

> Je vais donc les modifier directement dans la page.

Je ne comprends pas cette phrase. Que compte-tu faire ?

Pour rappel, il a été décidé lors de la réunion du 17 octobre que les définitions atemporelles et textes temporels de la M52 pouvaient attendre après le 9 novembre. 

Concernant modifier les titres de la M52, une issue est déjà ouverte, voir #339

**Comment by akakeronos** [comment]
Les définitions et les textes ok mais les libellés ? Il a été également décidé lors de cette réunion de remplacer les libellés génériques par des libellés plus significatifs comme remplacer enseignement par collèges par exemple

**Comment by akakeronos** [comment]
Je vais donc les modifier directement dans la page.

     Je ne comprends pas cette phrase. Que compte-tu faire ?
Les modifier directement dans le code de la page explorer
