### ISSUE TITLE
M52-DF-R2 lien M52 page explorer ne fonctionne pas

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#362]
Depuis la home le lien vers https://dtc-innovation.github.io/dataviz-finances-gironde/public/#!/finance-details/M52-DF-R2 ne fonctionne pas

**Comment by DavidBruant** [comment]
Duplicata de #242
Dans la mesure du possible, merci de vérifier s'il n'existe pas déjà une issue couvrant le problème avant d'en créer une autre, merci.
