### ISSUE TITLE
Mettre à jour les identifiants pour le déploiement

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#374]
Url | Nom du fichier |
-- | -- |
/media/2459/field_dataviz_files/0 | cedi_2012_CA.csv |   
/media/2459/field_dataviz_files/1 | cedi_2013_CA.csv |     
/media/2459/field_dataviz_files/2 | cedi_2014_CA.csv |     
/media/2459/field_dataviz_files/3 | cedi_2015_CA.csv |     
/media/2459/field_dataviz_files/4 | cedi_2016_CA.csv |     
/media/2459/field_dataviz_files/5 | Insertion.svg |   
/media/2459/field_dataviz_files/6 | bonhomme.svg |   
/media/2459/field_dataviz_files/7 | EnvironnementAmenagement.svg |   
/media/2459/field_dataviz_files/8 | Colleges.svg |   
/media/2459/field_dataviz_files/9 | Enfance.svg |     
/media/2459/field_dataviz_files/10 | Handicapes.svg |   
/media/2459/field_dataviz_files/11 | Patrimoine.svg |    
/media/2459/field_dataviz_files/12 | routes.svg |  
/media/2459/field_dataviz_files/13 | SoutienCommunes.svg |   
/media/2459/field_dataviz_files/14 | Personnesagees.svg |  
/media/2459/field_dataviz_files/15 | AgentesDepartement.svg |  
/media/2459/field_dataviz_files/16 | Carburant.svg |  
/media/2459/field_dataviz_files/17 | depensesElectricite.svg |   
/media/2459/field_dataviz_files/18 | m52-fonctions-atemporal.csv |   
/media/2459/field_dataviz_files/19 | corrections-agregation.csv |   
/media/2459/field_dataviz_files/20 | aggregated-temporal.csv |   
/media/2459/field_dataviz_files/21 | aggregated-atemporal.csv |   
/media/2459/field_dataviz_files/22 | polyfill.script |   
/media/2459/field_dataviz_files/23 | carte-presence.script |   
/media/2459/field_dataviz_files/24 | dataviz-finance-gironde-fr-bundle.script |   
/media/2459/field_dataviz_files/25 | public.css |

**Comment by akakeronos** [comment]
je viens de mettre à jour la prod et je n'ai plus rien qui s'affiche

**Comment by DavidBruant** [comment]
Dans le HTML de la prod, je peux lire

```html
<div class="cd33-finance-dataviz"></div>
<script src="/media/2459/field_dataviz_files/5"></script>
<script src="/media/2459/field_dataviz_files/6"></script>
<link rel="stylesheet" href="/media/2459/field_dataviz_files/7" type="text/css">
```

`/5`, `/6` et `/7` ne correspondent pas aux identifiants des scripts et CSS définis dans le media dataviz (resp `/22` `/24` et `/25`)

**Comment by akakeronos** [comment]
Effectivement j'avais oublié ce paramètre. Malheureusement cela ne marche pas mieux après l'avoir modifié. Je dois sûrement louper quelque chose d'évident

**Comment by DavidBruant** [comment]
Dans le HTML de la prod, je peux lire 

````html
 <div class="cd33-finance-dataviz"></div>
<script src="/media/2459/field_dataviz_files/22></script>
<script src="/media/2459/field_dataviz_files/24"></script>
<link rel="stylesheet" href="/media/2459/field_dataviz_files/25" type="text/css">
````

Il manque un `"` fermant sur l'attirbut `src` du premier `<script>`

**Comment by akakeronos** [comment]
merci

**Comment by akakeronos** [comment]
ça fonctionne merci
