### ISSUE TITLE
permettre d'ouvrir des liens dans un nouvel onglet en markdown

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#377]
Est-ce que la syntaxe [link](url){:target="_blank"} fonctionnera dans les définitions ?

**Comment by DavidBruant** [comment]
Le parser utilisé est celui-ci : https://github.com/markdown-it/markdown-it
Je peux lire la doc ou le code pour trouver la réponse, mais il serait plus facile de tester directement.

**Comment by akakeronos** [comment]
Je viens de le faire mais apparemment ce n'est pas interprété
https://www.gironde.fr/le-departement/un-budget-au-service-des-solidarites-humaine-et-territoriale#!/finance-details/DF-2-3

**Comment by akakeronos** [comment]
J'ai trouvé ça qui semble montrer que l'on peut https://www.npmjs.com/package/markdown-it-link-attributes

**Comment by DavidBruant** [comment]
Ce paquet permet d'ajouter des attributs aux liens (je me demandais si ça existait d'ailleurs, merci de l'avoir trouvé :-) )
Par contre, ce paquet ne sert pas à interpréter la syntaxe `{:target="_blank"}` de ce que j'en comprends.

**Comment by thom4parisot** [comment]
C'est exact @DavidBruant, le paquet ne permet pas d'ajouter des attributs sur les liens écrits.
[markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs) le permet en revanche.

Par contre je me rends compte qu'il y a un attribut de configuration [`pattern`](https://www.npmjs.com/package/markdown-it-link-attributes#pattern) qui permettrait d'ajouter _blank sur des liens sortants (l'exemple du README mentionne `noopener` aussi).

**Comment by DavidBruant** [comment]
La décision prise le 6 novembre était d'attribuer à tous les liens générés de Markdown `target=_blank`

**Comment by DavidBruant** [comment]
> l'exemple du README mentionne `noopener` aussi

Oui, c'est juste trop cool, c'est exactement pour ce cas que je cherchais à rajouter des attributs aux liens.

@akakeronos comme le précise Thomas, il existe une manière de n'appliquer le `target=_blank` que à certains liens via l'option "pattern" https://www.npmjs.com/package/markdown-it-link-attributes#pattern

Pas urgent vu la décision, mais je précise juste que l'option existe.
