### ISSUE TITLE
Transférer ce repo sur une propriété de la Gironde, recréer ce repo et faire un redirect

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#408]
http://objectifaquitaine.latribune.fr/innovation/2017-11-20/open-data-la-gironde-recompensee-pour-son-portail-budgetaire-758581.html a une lien vers https://dtc-innovation.github.io/dataviz-finances-gironde/public/ alors que cette URL ne devait rester qu'une URL de dév et pas de prod.

Une solution peut consister à transférer ce repo à la Gironde, puis le recréer et avoir une page web qui a un "meta refresh" qui redirige vers la bonne page en prod

**Comment by akakeronos** [comment]
oui je viens de voir le même lien sur la page de la gazette des communes. A l'époque où j'ai soumis le dossier je ne connaissais pas l'url de prod et je n'ai pas pensé à leur transmettre la définitive lorsque je l'ai connue. C'est couillon
Je comprends bien la première partie de ton message mais ensuite je ne vois pas le détail de la mise en oeuvre de la seconde :) Je suis pas sûr de savoir faire ça. Je suis pas sûr que la Gironde ait un repo mais j'en administre un pour l'organisation datalocale. 
Est-ce que tu peux m'aider à faire ça rapidement ?

**Comment by DavidBruant** [comment]
> oui je viens de voir le même lien sur la page de la gazette des communes. A l'époque où j'ai soumis le dossier je ne connaissais pas l'url de prod et je n'ai pas pensé à leur transmettre la définitive lorsque je l'ai connue. C'est couillon

Padprob !

> Je comprends bien la première partie de ton message mais ensuite je ne vois pas le détail de la mise en oeuvre de la seconde :)

Cette seconde partie est à faire par dtc. En gros, il s'agit de faire que si des gens cliquent sur le lien dtc-innovation.github.io, ils soient automatiquement redirigés vers la bonne page sur gironde.fr. Je ferai cette partie avec un [Meta refresh](https://en.wikipedia.org/wiki/Meta_refresh#Examples)

> Est-ce que tu peux m'aider à faire ça rapidement ?

Yes, on peut regarder ça demain (mardi) matin

**Comment by akakeronos** [comment]
Ok merci :) Je suis dispo vers 11h si ça te va.

**Comment by DavidBruant** [comment]
Pour le transfert, tout devrait bien se passer. Les seuls trucs qu'il faudra peut-être retravailler un peu sont : 
* recréer et publier un gh-pages
* lien avec Travis CI à recréer (dont un token si on veut toujours une version de démo)

**Comment by DavidBruant** [comment]
Le transfert est fait, le redirect est en place. 
Concernant Travis CI, ça fera partie des discussions sur la transmission (vu que le CD33 a une preprod, est-il crucial d'avoir Travis CI + démo sur datalocale.github.io, etc.)

**Comment by akakeronos** [comment]
Merci. En parallèle les liens des articles de la tribune et de la gazette ont été modifié donc c'est corrigé, merci
