### ISSUE TITLE
supprimer l'affichage des données d'ordre dans la navigation M52

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#422]
- [x] supprimer l'affichage des données d'ordre dans les pages de la navigation par fonction

**critères d'acceptation:**
- [x] les données n'apparaissent plus dans le site de production
- [ ] les données n'apparaissent plus si on charge des CA des années antérieures
- [ ] les données n'apparaissent plus si on charge le CA 2017

**Comment by DavidBruant** [comment]
Note : https://github.com/datalocale/dataviz-finances-gironde/blob/4f1cd6b441f9655869e81ad7e525d29136721cac/src/shared/js/finance/hierarchicalM52.js#L34 
Il faut enlever ce qui n'est pas un ordre réel à cet endroit.
Faisons-le jeudi

**Comment by akakeronos** [comment]
correction mise en production ce jour. Pour les 2 derniers critères d'acceptation il faut avoir les données du CA 2017
