### ISSUE TITLE
commande de build pour la pre-prod

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#433]
Je voudrais charger la nouvelle version utilisant le fichier json en prod mais je dois faire un détour pour la pre-prod pour m'assurer que l'outil est bien capable de consommer le fichier json associé au media drupal sans le type mime associé.
Pourriez-vous me rappeler la commande de build spécifique au contexte gironde-preprod afin que je puisse tester ce contexte de déploiement ?

**Comment by DavidBruant** [comment]
La commande de build pour la preprod est `npm run build-preprod`

On peut retrouver cette information dans le readme du projet : https://github.com/datalocale/dataviz-finances-gironde#d%C3%A9ploiement
