### ISSUE TITLE
impossible d'effectuer les commandes build sur mon poste

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#434]
Je ne comprends pas du tout pourquoi mais ce matin je ne parviens plus à effectuer les commandes de build
J'ai l'erreur suivante 

module.js:472
    throw err;
    ^
Error: Cannot find module './polyfill'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> 
(D:\Donnees\Documents\GitHub\dataviz-finances-gironde\node_modules\npm-run-all\node_modules\string.prototype.padend\index.js:8:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

J'ai tenté de désinstaller node.js et de le ré-installer et de faire une commande de mise à jour mais je ne sais pas quoi faire d'autre

**Comment by akakeronos** [comment]
quand je lance npm install après la ré-installation de npm j'ai ce message

npm : npm WARN rollback Rolling back tar-pack@3.4.0 failed (this is probably harmless): EPERM: operation not permitted, scandir 
'D:\Donnees\Documents\GitHub\dataviz-finances-gironde\node_modules\fsevents\node_modules'
Au caractère Ligne:1 : 1
+ npm install
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN rollba...s\node_modules':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm
 
WARN
 
optional
 SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm
 
WARN
 
notsup
 SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: 
{"os":"win32","arch":"x64"})
up to date in 153.219s

**Comment by DavidBruant** [comment]
Je n'ai pas assez d'information pour comprendre le problème et donc aider à sa résolution.
De ce que je lis dans le second message, il s'agit d'un problème de permissions sur les fichiers.

On peut s'appeler demain si tu n'as pas trouvé de solution d'ici là. Ma seule dispo est à 9h-Ca/15h-Fr

**Comment by akakeronos** [comment]
ok je veux bien car je ne saurais pas m'en sortir tout seul je pense
