### ISSUE TITLE
Problème de déploiement

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#435]
> La mise à jour en pre-prod ne fonctionne pas pour l'instant
> J'ai 2 messages d'erreur et rien ne s'affiche sur la page.
> J'ai effectué la commande de build pour la pre-prod et chargé les 2 fichiers générés ainsi que le fichier json
>
> Échec du chargement pour l’élément <script> dont la source est « https://gironde-preprod.cg33.fr/media/1938/field_dataviz_files/7
> Échec du chargement pour l’élément <script> dont la source est « https://gironde-preprod.cg33.fr/media/1938/field_dataviz_files/5
> 
> L'agencement des médias associés à https://gironde-preprod.cg33.fr/media/1938 est le même que pour la prod

https://github.com/datalocale/dataviz-finances-gironde/pull/432#issuecomment-365865489

**Comment by DavidBruant** [comment]
Je soupçonne que précédemment le script de polyfills et le script principale avaient les identifiants `7` et `5`. Ils ont désormais les identifiants `17` et `19`.

Je pense qu'en mettant à jour le "bloc HTML" avec les bons identifiants, ce problème va se résoudre.

**Comment by akakeronos** [comment]
> Je pense qu'en mettant à jour le "bloc HTML" avec les bons identifiants, ce problème va se résoudre.
Je ne sais pas ce que tu veux dire par bloc HTML

**Comment by DavidBruant** [comment]
Il s'agit du morceau de HTML qui est rajouté dans Drupal pour que la page s'affiche. Je ne sais plus si le nom est "Bloc HTML" ou "Bloc HTML5"

**Comment by akakeronos** [comment]
je viens de comprendre :)

**Comment by akakeronos** [comment]
ça fonctionne ! Merci
