### ISSUE TITLE
rajouter des sommes en dur dans le calcul des montants agrégés

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#436]
Je voudrais pouvoir ajouter une somme "en dur" en attendant que le cadre comptable puisse prendre en compte des modifications d'imputations
Apparemment il y a des exemples dans m52ToAgregated.js pour les sections DF-1-1-3 et DF-1-5 mais dans le code je ne vois pas de somme indiquée. Il faudrait rajouter une somme dans RF-6-5

**Comment by DavidBruant** [comment]
Le service des finances est désormais autonome sur ce sujet-là
