### ISSUE TITLE
problème d'imputation de recettes sociales sur les autres produits de gestion courante (RF-9-7)

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#437]
Le montant de https://gironde-preprod.cg33.fr/le-departement/le-budget#!/finance-details/RF-9-7 est différent du montant de https://www.gironde.fr/un-budget-au-service-des-solidarites-humaine-et-territoriale#!/finance-details/RF-9-7

Ce qui fait la différence sont les articles de la fonction 5 qui devraient être en RF-6-5 et qui se retrouvent en RF-9-7. 
Actuellement lors du chargement avec les fichiers TOTEM ces montants sont comptés 2 fois alors que le montant de RF ne change pas 1527,4 €

**Comment by DavidBruant** [comment]
Je ne vois pas l'URL avec preprod, mais je vois le problème sur https://datalocale.github.io/dataviz-finances-gironde/public/#!/finance-details/RF-9-7

C'est cohérent avec ce qu'on peut observer sur [l'outil métier](https://datalocale.github.io/dataviz-finances-gironde/) : 
````
Lignes M52 utilisées dans au moins 2 formules d'aggrégation (5)

    R 551 7533 (92 073,68 €) utilisé dans RF-6-5, RF-9-7
    R 51 7512 (541 426,57 €) utilisé dans RF-6-5, RF-9-7
    R 52 7535 (143 566,28 €) utilisé dans RF-6-5, RF-9-7
    R 51 7511 (1 065 458,53 €) utilisé dans RF-6-5, RF-9-7
    R 5471 7531 (6 893,01 €) utilisé dans RF-6-5, RF-9-7
````

Il doit s'agir d'un bug de ma part introduit à l'occasion du refactoring. J'étudie le problème et je trouve une correction rapidement

**Comment by DavidBruant** [comment]
Le service des finances est désormais autonome sur ce sujet-là
