### ISSUE TITLE
les tests de build échouent suite aux modifications sur les formules

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#440]
J'ai réussi (je pense) à corriger le problème de syntaxe sur le fichier d'aggrégat et le projet build en local sur mon ordi.
En revanche il ne builde pas sur github car les tests associés échouent.
Peut-être que les nouvelles formules sont incorrectes mais je ne pourrais pas le savoir avant d'avoir retravaillé avec Laurence sur mon poste.

**Comment by thom4parisot** [comment]
Salut Pascal,

j'ai jeté un œil et à en lire [ce bloc](https://travis-ci.org/datalocale/dataviz-finances-gironde/builds/344244861#L479-L488)

```
> browserify src/m52-overview/js/main.js -o build/m52-overview-bundle.js -d
SyntaxError: /home/travis/build/datalocale/dataviz-finances-gironde/src/shared/js/finance/m52ToAggregated.js: Unexpected token, expected , (1028:1)
  1026 |             }
  1027 |         }
> 1028 | };
       |  ^
  1029 | 
  1030 | 
  1031 | 
```

Y'a une erreur de syntaxe donc peut-être qu'il manque un caractère ou deux — ou qu'y en a un ou deux en trop quelque part.

**Comment by akakeronos** [comment]
Salut Thomas,
J'avais effectivement cette même erreur sur mon poste et je pensais l'avoir corrigé. 
Elle n'apparaît plus sur mon EsLint dans Atom et le projet se lance correctement en local sur mon poste (npm run watch s'exécute et je peux voir l'outil métier et la dataviz)
Les erreur de buils me semblent plus liées à des erreurs dans le contenu des formules mais je ne suis pas sûr à 100%
