### ISSUE TITLE
confirmation du bon ordre pour mettre à jour

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#455]
@DavidBruant je pense que les modifications ont été faites dans la PR #454  pour pouvoir mettre à jour la démo.
Je pense que ma version locale est correctement synchronisée avec chaque modification associée à une branche. Je voudrais donc récupérer la version distante master pour récupérer les modifications des formules en local avec tes ajouts et générer un build pour la production. 
L'idée serait de mettre à jour enfin la version de prod avec les formules corrigées puis de continuer à travailler avec l'environnement de démo pour le reste des modifications à apporter pour avril.
Je pensais me positionner sur la branche master récupérer la version distante de master puis faire un 
  npm run build:production
Est-ce que cela te paraît correct ?

**Comment by DavidBruant** [comment]
> @DavidBruant je pense que les modifications ont été faites dans la PR #454 pour pouvoir mettre à jour la démo.

Nan, le projet ne build pas à cause d'un fichier mal nommé : https://github.com/datalocale/dataviz-finances-gironde/pull/454#discussion_r173002329

Essaye de faire fonctionner le projet en local où tu vois réellement des graphiques avec les années 2013-2017. Une fois que ça marchera en local, nous aurons une confiance élevée que ça fonctionne pour la version démo.

**Comment by DavidBruant** [comment]
Une fois que la version démo (datalocale.github.io) marchera, on considèrera pousser en pré-production et/ou production sur gironde.fr

**Comment by DavidBruant** [comment]
Je pense que c'est désormais résolu
