### ISSUE TITLE
affichage des données sur la home et la page explorer 

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#456]
Je viens de lancer le projet en local et je constate plusieurs soucis

 *   la valeur du montant des dépenses sur la page d'accueil ne s'affiche pas
 *  les valeurs du bloc les grands masses budgétaires affichent NaN
 *  Les années sous les histogrammes affichent la période 2012-2016

**Comment by DavidBruant** [comment]
Actuellement, sur la [version déployée](https://datalocale.github.io/dataviz-finances-gironde/public/), je vois les choses suivantes : 

![capture d ecran de 2018-03-07 18-00-51](https://user-images.githubusercontent.com/165829/37123263-8b404bf6-2231-11e8-97b0-4b21a7c79317.png)
![capture d ecran de 2018-03-07 18-00-17](https://user-images.githubusercontent.com/165829/37123267-8c326c60-2231-11e8-8548-d0956f7dc61f.png)
![capture d ecran de 2018-03-07 18-00-04](https://user-images.githubusercontent.com/165829/37123268-8c7104d4-2231-11e8-873d-174160bdc79a.png)


![capture d ecran de 2018-03-07 18-00-38](https://user-images.githubusercontent.com/165829/37123265-8b7f9fa4-2231-11e8-9891-be3156249c3c.png)
![capture d ecran de 2018-03-07 18-00-33](https://user-images.githubusercontent.com/165829/37123266-8bbd4ae8-2231-11e8-8cf2-5674c230abfe.png)

Je ne sais pas quel problème tu rencontres en local, mais ce qui est actuellement sur master a l'air de marcher comme attendu

**Comment by akakeronos** [comment]
tant mieux 👍 🥇
