### ISSUE TITLE
il manque des légendes pour des articles ajoutés sur la page finance-details

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#457]
Pour les articles ajoutés en 2017 on ne trouve pas les légendes associées dans l'histogramme de la page finance-details.
Par exemple sur https://datalocale.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-6 pour l'article DF-6-4 ou https://datalocale.github.io/dataviz-finances-gironde/public/#!/finance-details/DF-1 pour l'article DF-1-8

**Comment by DavidBruant** [comment]
A priori, on est bons niveau légendes
