### ISSUE TITLE
régler le problème de cohérence entre les chiffres dans les finances-details

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#461]
* [ ] doit systématiquement afficher les mêmes chiffres dans la partie supérieur de la page et ceux présents sur l'histogramme

Note  : j'ai effectué un 1er contrôle et je trouve une dépense de 16.65M€ en trop sur la section DF.

En dépenses totales on devrait avoir 1659.5M€ et pas 1676.2M€.

C'est des dépenses de fonctionnement et en DF on devrait avoir 1408.8M€ et pas 1425M€. par contre le graphique remonte les bonnes données

j'ai peut être une piste : le montant ressemble à ce qu'on a saisi en dur hier soir sur les imputations D51 65111 en DF1

**Comment by akakeronos** [comment]
@DavidBruant est-ce que cela te dit quelque chose ? Le chiffre du haut de la page finance-details est différent du chiffre affiché sur l'histogramme

**Comment by pointbar** [comment]
- [ ] doit afficher les même chiffres que sur l'histogramme

**Comment by DavidBruant** [comment]
J'ai trouvé d'où vient le problème.
Le fichier CA2017 nous informe que `D 51 65111` a un montant de `16 625 479,71€`. Ce montant est dans `DF-2-4`. Le [fichier de corrections](https://github.com/datalocale/dataviz-finances-gironde/blob/1c50ca70689f8f2f748e04f20d50ab1b4cd2ff90/data/finances/corrections-agregation.csv) contient les lignes suivantes pour la répartition dans `DF-1` : 

```csv
Exer,CodRD,FI,Chapitre,Nature,Fonction,MtReal,Identifiant agrégé
2017,D,F,65,65111,51,12369182.09,DF-1-1-3
2017,D,F,65,65111,51,4256297.6,DF-1-5
```

Achtung, c'est très subtile ! `12369182.09 + 4256297.6 = 16625479.69` (`16 625 479,69€`). Il y a donc une différence de 2 centimes entre la ligne dans le CA et le découpage dans les corrections.

Cette différence de montant amène le [logiciel tel qu'actuellement codé](https://github.com/datalocale/dataviz-finances-gironde/blob/1c50ca70689f8f2f748e04f20d50ab1b4cd2ff90/src/shared/js/finance/hierarchicalAggregated.js#L279) à déduire que ces lignes (la ligne `D 51 65111` dans `DF-2-4` et les lignes dans `DF-1-1-3` et `DF-1-5`) n'ont rien à voir les unes avec les autres et doivent donc être comptées indépendamment dans le total final.

Ma recommandation pour la correction, c'est de voir avec les finances d'où vient cette différence de 2c et corriger soit le fichier du CA 2017 soit le fichier de correction. Une fois les données corrigées, l'affichage devrait être corrigé.

**Comment by akakeronos** [comment]
ok merci! Je viens de modifier le montant pour DF-1-1-3

**Comment by DavidBruant** [comment]
Problème corrigé dans https://github.com/datalocale/dataviz-finances-gironde/commit/c4ba98d7fe11747af8aecbe96a65a33af9407420
