### ISSUE TITLE
Produire une formule pour la section DF-1-8

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#467]
* [ ] doit permettre d'obtenir les sommes de 2 664 431 € pour 2016 et 4 612 293 € pour 2017

Notes : 

* La formule métier est 
(A65113 * F 53) + ((A65113 + A6568) des fonction 531 et 532)

* le code actuel est https://gist.github.com/akakeronos/263e2deb53f50d6eff67e2d49ea0b747

**Comment by DavidBruant** [comment]
Il s'agit d'un changement dans DF-1, je soupçonne qu'il devrait s'accompagner d'un changement quelque part dans DF-2 ?

**Comment by DavidBruant** [comment]
Corrigé dans #488
