### ISSUE TITLE
vérifier la bonne exécution des variables intégrées pour changer les formules entre 2016 et 2017

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#468]

**Comment by pointbar** [comment]
- [ ] doit permettre de vérifier que D 51 65111 (16 567 824,62 €)  est présent dans DF-1 et DF-2
- [ ] doit permettre de vérifier que D 50 6451 , D 50 6453 et D 50 6454 est utilisés en 2016

**Comment by DavidBruant** [comment]
On observe sur l'outil métier datalocale.github.io pour le CA 2017 une incohérence autour de `D 51 65111`, mais a priori, ce problème ne s'observe pas sur la viz publique.

A priori, les considérations autour de `D 50` pour 2016 ne s'observent pas sur l'outil métier ni la viz publique.

**Comment by DavidBruant** [comment]
Les formules sont corrigées et sous la responsabilité du service finances qui est désormais autonome sur le sujet
