### ISSUE TITLE
permettre la gestion de définitions conjoncturelles et des indicateurs par année

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#469]
ETQ Direction des finances je veux pouvoir stocker des définitions conjoncturelles associée à une année pour pouvoir permettre à terme d'afficher plusieurs versions de la dataviz par année

* [ ] doit permettre de gérer des définitions conjoncturelles par année
* [ ] doit permettre de stocker des indicateurs associés (dans les pages focus) par année du CA

**Comment by DavidBruant** [comment]
Je crois que ça n'est plus d'actualité
