### ISSUE TITLE
ajouter la section DI-1-5 dans la page focus investissement

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#470]
* [ ] doit afficher la valeur de la section DI-1-5 dans l'histogramme de la page focus récapitulant les sections d'investissement

**Comment by DavidBruant** [comment]
Juste pour le signifier, modifier seulement l'histogramme signifie qu'il n'y a pas de section en-dessous qui explique ce qu'est "Autres (PPP...)"

**Comment by akakeronos** [comment]
Merci pour ce rappel. En revanche il me semble que le code couleur n'est pas raccord avec la couleur de cette section dans la navigation. Désolé ce n'était pas dans les critères d'acceptation.
