### ISSUE TITLE
transcription en code de formules financières exprimées en language métier

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#504]
ETQ agent des finances je veux pouvoir saisir des formules d'agrégats en language pseudo naturel (genre DF*(F4) ) afin de pouvoir consulter le résultat et en cas de conformité avec le résultat attendu l'enregistrer dans le code de l'application

- [ ] doit permettre de saisir des formules d'agrégats financiers et de consulter pour 2 années consécutives du CA le montant obtenu
- [ ] doit permettre d'exprimer simplement les différents cas d'agrégats
- [ ] doit permettre d'enregistrer dans un fichier la formule d'agrégats définie en l'affectant à un des niveaux d'agrégats
- [ ] doit permettre de charger une configuration afin d'y apporter des ajustements

**Comment by acidjames** [comment]
Est-ce qu'on peut ajouter la fonctionnalité suivante : 

- [] doit permettre de charger une configuration afin d'y apporter des ajustements
