### ISSUE TITLE
Fichiers liste ordonnée des "codes" (données aggrégées ou M52)

### ISSUE THREAD

**Issue by vinber** [datalocale/dataviz-finances-gironde#51]
Idée / Je ne sais pas si c'est le lieu mais cela m'oblique à l'écrire ? Et peut-être que c'est ce que vous avez prévu ?

Générer des fichiers avec la liste des codes M52, aggrégé, type markdown, pour que l'on puisse commencer à remplir des "zones" de texte, qui seront ensuite être "affiché" dans la viz ou dans un composant ?

Par exemple, on a par défaut dans le fichier des codes de la DFI :
le code, le titre métier, le titre public, l'explication, le contexte
Par défaut on a donc code et titre métier.
On peut commencer à surcharger avec des titres plus compréhensibles sur les thématiques demandées ?

Idem pour la M52
par défaut un fichier brut avec la nomenclature officielle mais avec des possibilités de rajouter des infos titre public, explication, le contexte

**peut-être que c'est juste pour clarifier dans ma tête :)** donc on peut effacer en suivant !

**Comment by DavidBruant** [comment]
> Générer des fichiers avec la liste des codes M52, aggrégé, type markdown, pour que l'on puisse commencer à remplir des "zones" de texte, qui seront ensuite être "affiché" dans la viz ou dans un composant ?

A priori, ça ne sera pas un markdown avec les codes comme titre de section, parce que ça serait dur à reparser pour nous derrière. Partons plutôt sur un tableau (exporté plus tard en csv) où y'a une colonne avec les codes et une colonne avec du contenu (ou une colonne label + une colonne contenu). Et un autre tableur avec les textes spécifiques à une année. Vous pouvez mettre du markdown dans les colonnes de texte ;-)
Dans ces conditions-là, pas besoin de code, vous pouvez travailler sur le contenu textuel de manière indépendante et on fait juste un extrait csv quand on se sent bien pour le donner à manger au code.

J'ai une large préférence pour que vous travailliez sur un tableur en ligne (google spreadsheet ou framacalc) qui permet l'export en CSV.

**Comment by DavidBruant** [comment]
Le tableau a été mis en place.
Pour la M52, les fonctions sont là https://github.com/dtc-innovation/dataviz-finances-gironde/blob/master/src/shared/js/finance/m52FonctionLabels.json
Les articles ne sont pas là, mais pas nécessaires pour le moment non plus.
