### ISSUE TITLE
déploiement local

### ISSUE THREAD

**Issue by akakeronos** [datalocale/dataviz-finances-gironde#514]
Lors du déploiement du projet sur ma machine j'ai des erreurs et je ne peux pas visualiser l'interface /public
J'ai redeployé le projet de zéro en clonant le dépôt et en suivant les instructions du readme

l'interface avec les sunburst ne s'affiche plus alors qu'hier elle s'affichait

silly fetchPackageMetaData error for file:romain\AppData\Roaming\npm-cache\_npx\638724 Could not install from "romain\AppData\Roaming\npm-cache\_npx\638724" as it does not contain a package.json file.

[2019-04-04T11_30_45_897Z-debug.log](https://github.com/datalocale/dataviz-finances-gironde/files/3043220/2019-04-04T11_30_45_897Z-debug.log)
[2019-04-04T11_31_39_581Z-debug.log](https://github.com/datalocale/dataviz-finances-gironde/files/3043221/2019-04-04T11_31_39_581Z-debug.log)

**Comment by akakeronos** [comment]
Je viens d'essayer à nouveau sur un linux et j'ai les mêmes erreur

keronos@olga-ordi:~/gitlab/dataviz-finances-gironde$ npm run watch

> dataviz-gironde@1.0.0 watch /home/keronos/gitlab/dataviz-finances-gironde
> npm-run-all --parallel watch:*

> dataviz-gironde@1.0.0 prewatch:public /home/keronos/gitlab/dataviz-finances-gironde
> npm run build:public:data:m52-strings

> dataviz-gironde@1.0.0 watch:m52overview /home/keronos/gitlab/dataviz-finances-gironde
> cross-env NODE_ENV=development watchify --iw **/node_modules/** src/m52-overview/js/main.js -o build/m52-overview-bundle.js -d -v

> dataviz-gironde@1.0.0 prebuild:public:data:m52-strings /home/keronos/gitlab/dataviz-finances-gironde
> npm run prepare:plan-de-compte

> dataviz-gironde@1.0.0 prepare:plan-de-compte /home/keronos/gitlab/dataviz-finances-gironde
> npx github:dtc-innovation/plans-de-compte --in data/finances/CA --out data/finances/plansDeCompte

sh: 1: npx: not found

npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "prepare:plan-de-compte"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! dataviz-gironde@1.0.0 prepare:plan-de-compte: `npx github:dtc-innovation/plans-de-compte --in data/finances/CA --out data/finances/plansDeCompte`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the dataviz-gironde@1.0.0 prepare:plan-de-compte script 'npx github:dtc-innovation/plans-de-compte --in data/finances/CA --out data/finances/plansDeCompte'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dataviz-gironde package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npx github:dtc-innovation/plans-de-compte --in data/finances/CA --out data/finances/plansDeCompte
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dataviz-gironde
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dataviz-gironde
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keronos/gitlab/dataviz-finances-gironde/npm-debug.log

npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:public:data:m52-strings"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! dataviz-gironde@1.0.0 prebuild:public:data:m52-strings: `npm run prepare:plan-de-compte`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dataviz-gironde@1.0.0 prebuild:public:data:m52-strings script 'npm run prepare:plan-de-compte'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dataviz-gironde package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prepare:plan-de-compte
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dataviz-gironde
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dataviz-gironde
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keronos/gitlab/dataviz-finances-gironde/npm-debug.log

npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/node" "/usr/share/npm/bin/npm-cli.js" "run" "watch:public"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! dataviz-gironde@1.0.0 prewatch:public: `npm run build:public:data:m52-strings`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dataviz-gironde@1.0.0 prewatch:public script 'npm run build:public:data:m52-strings'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dataviz-gironde package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:public:data:m52-strings
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dataviz-gironde
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dataviz-gironde
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keronos/gitlab/dataviz-finances-gironde/npm-debug.log
ERROR: "watch:public" exited with 1.

npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! dataviz-gironde@1.0.0 watch: `npm-run-all --parallel watch:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dataviz-gironde@1.0.0 watch script 'npm-run-all --parallel watch:*'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dataviz-gironde package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel watch:*
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dataviz-gironde
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dataviz-gironde
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keronos/gitlab/dataviz-finances-gironde/npm-debug.log

**Comment by DavidBruant** [comment]
> npx: not found

> npm ERR! npm v3.5.2

[npx a été ajouté avec npm 5.2.0](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b)

Une solution, c'est de mettre à jour node/npm

J'ai une autre solution qui est facile à mettre en place et retire le besoin de npx

**Comment by akakeronos** [comment]
je viens de mettre à jour et j'ai maintenant npm 6.9.0

j'ai toujours une erreur

12 verbose stack Error: dataviz-gironde@1.0.0 prepare:plan-de-compte: `npx github:dtc-innovation/plans-de-compte --in data/finances/CA --out d
ata/finances/plansDeCompte`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at EventEmitter.emit (events.js:214:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid dataviz-gironde@1.0.0
14 verbose cwd /home/keronos/gitlab/dataviz-finances-gironde
15 verbose Linux 4.15.0-47-generic
16 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "prepare:plan-de-compte"
17 verbose node v8.10.0
18 verbose npm  v6.9.0
19 error code ELIFECYCLE
20 error errno 1
21 error dataviz-gironde@1.0.0 prepare:plan-de-compte: `npx github:dtc-innovation/plans-de-compte --in data/finances/CA --out data/finances/pl
ansDeCompte`
21 error Exit status 1
22 error Failed at the dataviz-gironde@1.0.0 prepare:plan-de-compte script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

peut-être parce que le script pointe vers le dépôt dtc-innovation ?

**Comment by DavidBruant** [comment]
Je viens d'essayer avec Travis de lancer le projet avec Node.js 8 (qui a l'air d'être ta version `17 verbose node v8.10.0`)
Versions précises : 
```sh
$ node --version
v8.15.1
$ npm --version
6.4.1
```

Le build a l'air de bien se passer : https://travis-ci.org/datalocale/dataviz-finances-gironde/jobs/518249905

**Comment by akakeronos** [comment]
ça avance mais j'ai toujours une erreur lors de l'exécution de la commande npm run watch

Error: Cannot find module '../../../build/finances/m52-strings.json' from '/home/keronos/gitlab/dataviz-finances-gironde/src/public/js'
Error: Cannot find module '../../../../build/finances/m52-strings.json' from '/home/keronos/gitlab/dataviz-finances-gironde/src/shared/js/finance'
Error: Cannot find module '../../../../../build/finances/m52-strings.json' from '/home/keronos/gitlab/dataviz-finances-gironde/src/public/js/components/screens'
Error: Cannot find module '../../../build/finances/m52-strings.json' from '/home/keronos/gitlab/dataviz-finances-gironde/src/public/js'
Error: Cannot find module '../../../../build/finances/m52-strings.json' from '/home/keronos/gitlab/dataviz-finances-gironde/src/shared/js/finance'
