### ISSUE TITLE
Corriger les identifiants

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#520]
Jusque-là, il y avait beaucoup d'identifiants genre `DF-1-7-2`. Les `-` ont été remplacés par des `.`

De tête, les endroits à corriger :
- fichier de corrections
- textes atemporels
- textes temporels
- tests automatisés
- code d'affichage
- page focus

**Comment by akakeronos** [comment]
C'est une tâche pour moi ? ou c'est juste un mémo ?

**Comment by DavidBruant** [comment]
Il s'agit d'une tâche qui, si elle n'est pas faite, empêchera un fonctionnement correct de l'application après la mise en place de l'agrégation telle que définie par le service des finances avec l'outil dédié

> pour moi ?

Je n'ai pas réfléchis à cette question
