### ISSUE TITLE
Outil métier : les deux sunburst ne tiennent pas sur l'écran sur Chrome

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#62]
Alors qu'on est bon sur Firefox.
Sûrement une mauvaise interaction flexbox + svg.

**Comment by thom4parisot** [comment]
Sur mon écran ça rentre pas par exemple.

![capture d ecran 2017-03-03 a 14 22 39](https://cloud.githubusercontent.com/assets/138627/23552562/e003dd8e-001c-11e7-8bd3-97afd0cc97ce.png)

**Comment by DavidBruant** [comment]
L'outil métier va disparaitre #527
