### ISSUE TITLE
Afficher l'équilibre budégtaire (recettes et dépenses totales) à partir des vraies données du CA 2015

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#65]

**Comment by thom4parisot** [comment]
@DavidBruant qu'est-ce que tu entends par là ? Ce n'est pas déjà ce qui est affiché avec le R•F du RDFI ?

**Comment by DavidBruant** [comment]
J'ai rephrasé l'issue pour que ça soit plus clair.

>  Ce n'est pas déjà ce qui est affiché avec le R•F du RDFI ?

L'idée, c'est de faire apparaitre l'équilibre budgétaire, donc le total des dépenses (DF + DI) et des recettes (RF + RI).
C'est une demande assez directe de la DFI et ça n'est pas déconnant. Partons là-dessus à défaut de mieux. On aura plus de retours et de participants à la discussion quand il y aura quelque chose sur lequel poser l'œil.
