### ISSUE TITLE
Créer et documenter le système qui permet de contribuer du contenu textuel

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#67]
Tout un tas de fichiers avec 2 colonnes : 
- identifiant
- texte

Liste des fichiers : 
Pour chaque identifiant de rubrique fonctionnelle M52 : 
- Un fichier qui associe une étiquette
- Un fichier qui associe un texte d'explication atemporel
- Un fichier par année qui associe un texte d'explication pour l'année concernée

Pour chaque identifiant de la vision agrégée : 
- Un fichier qui associe une étiquette
- Un fichier qui associe un texte d'explication atemporel
- Un fichier par année qui associe un texte d'explication pour l'année concernée

Soit au moins 4 fichiers + 2 fichiers pour 2015 (=6) à ce stade.

Les fichiers seront fournis en format .csv. Les textes peuvent être fournis sous format markdown. L'outil fera le rendu.

**Comment by vinber** [comment]
Soit les fichiers suivants :

- M52-etiquettes.csv
- M52-explication.csv
- M52-explication-2015.csv

- Agrege-etiquettes.csv
- Agrege-explication.csv
- Agrege-explication-2015.csv
