### ISSUE TITLE
Décider du workflow final de chargement des données

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#7]
Dans le déploiement final, doit-on aller chercher : 
* Les données copiées sur le serveur 
* Les données depuis datalocale (si les headers CORS sont ouverts)
?

Cache avec ServiceWorker ?

**Comment by DavidBruant** [comment]
https://trello.com/c/1GsVt8Ji/10-decider-d-ou-le-produit-final-tire-les-donnees

**Comment by thom4parisot** [comment]
Les données sont-elles susceptibles de changer après un déploiement ?

**Comment by DavidBruant** [comment]
C'est une des questions. Il est possible qu'on nous demande un outil qui va chercher des nouvelles données chaque année.
Aussi, comme on l'a vu avec l'encoding, il se peut que les fichiers changent un peu parfois. Mais c'est sensé être très rare.

**Comment by thom4parisot** [comment]
Travis.ci peut être utilisé en mode _cron_. Donc y'a tout à fait moyen de redéployer des données "fraiches" tous les jours. L'avantage c'est que le build lui-même garantit un rapport d'erreur et une intégrité de l'utilisation de l'outil (fraicheur des données mise à part).

**Comment by DavidBruant** [comment]
On se dirige vers une copie des fichiers CSV dans le CMS du Département.
Le plus gros problème avec datalocale, c'est que les URLs ne sont pas stables quand un fichier est ré-uploadé après une correction

**Comment by datalocale** [comment]
pour moi le lien dans la navigation au niveau des feuilles doit être https://www.datalocale.fr/dataset/comptes-administratifs-du-departement-de-la-gironde à moi de m'assurer qu'il est persistant. Pour le chargement des données il est effectivement peut-être plus raisonnable de privilégier une solution locale mais pourquoi pas sur le futur dépôt de source ?

**Comment by DavidBruant** [comment]
Après discussion avec @datalocale, nous allons faire la chose suivante : 
* l'URL https://www.datalocale.fr/dataset/comptes-administratifs-du-departement-de-la-gironde devient stable et permanente.
* Un point d'API basé sur cette URL permet de récupérer les meta-données sur les jeux de données : 
    * type de budget (CA, BP, etc.)
    * année
    * url du fichier csv
    * url de la ressource sur datalocale

A partir de ça, on peut : 
* charger les données directement à partir de datalocale (plutôt que github ou le CMS de gironde.fr)
* fournir le lien vers le fichier de la bonne année dans les pages feuilles

Le seul inconvénient de cette solution, c'est que le chargement des données prend 2 allers-retours. Ce n'est pas très grave dans l'absolu et peut être compensé par une bonne politique de cache surtout de la première URL dont la réponse peut être considérée valide assez longtemps (4h ?)

**Comment by DavidBruant** [comment]
https://www.datalocale.fr/api/3/action/package_show?id=comptes-administratifs-du-departement-de-la-gironde donne les méta données. Puis `.result.resources`. Ensuite, dans chaque ressource, `id`, `url`, `name` (pour l'année). Pour l'url de la ressource sur datalocale : 
`https://www.datalocale.fr/dataset/comptes-administratifs-du-departement-de-la-gironde/resource/${id}`

**Comment by datalocale** [comment]
avec la perspective de chargement des fichiers Totem il faudra sûrement privilégier le développement d'outils intermédiaires qui chargent et transforment les données
Il faut au moins faire un test de chargement d'une année depuis datalocale

**Comment by DavidBruant** [comment]
Désormais, les données sont préproduites avec un [outil de build dédié](https://github.com/datalocale/dataviz-finances-gironde/blob/master/tools/make-finance-data.js) à partir des fichiers XML
Ça génère un fichier JSON qui contient toutes les données financières à afficher
