### ISSUE TITLE
Page blanche lors de l'accès à dataviz-finances-gironde / Impossible d'accéder au contenu de la page 

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#75]
Impossible d'accéder au contenu de Dataviz Finances Gironde. La page reste blanche sous Firefox et Chrome. Problème rencontré le 6 mars 2017 à partir de 18h. Plusieurs connexions même résultat. 

J'utilise Firefox 51.0.1 (64 bits) 
![capture d ecran 2017-03-06 a 6 03 50 pm](https://cloud.githubusercontent.com/assets/23077793/23620975/32e239f0-0299-11e7-8412-7b2f93271183.png)
 et  Chrome Version 56.0.2924.87 (64-bit) 
![capture d ecran 2017-03-06 a 6 18 27 pm](https://cloud.githubusercontent.com/assets/23077793/23621014/51e49a5a-0299-11e7-9d79-6acdff5cd818.png)

Les captures d'écran ça sert à rien mais c'est cadeau.

**Comment by DavidBruant** [comment]
Yep, je confirme.

https://dtc-innovation.github.io/dataviz-finances-gironde/build/m52-overview-bundle.js donne du HTTP 404. Après inspection du `deploy.sh`, c'est normal. Le fichier dont on s'attendait qu'il soit dans `client/js` est désormais dans `build`, donc le script ne rajoute pas les bons fichiers, donc 404.

**Comment by DavidBruant** [comment]
J'ai corrigé le problème. Merci pour le report de bug :-)
