### ISSUE TITLE
Faire un outil de preprocessing pour bundler les données financières et textuelles

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/dataviz-finances-gironde#77]
C'est un peu une méta-issue à découper si nécessaire le jour où les idées/usages sont plus claires.

Le besoin s'est fait sentir à l'occasion de https://github.com/dtc-innovation/dataviz-finances-gironde/pull/76
Dans cette PR, on fetch 6 csv côté client. Ces 6 csv ont chacun du markdown qui est transformé en HTML côté client. Donc on perd en perf de chargement parce : 
- 6 requêtes HTTP
- on parse du csv (+ coût du code du parser)
- on parse du markdown (+ coût du code du parser)
- on modifie la structure de données (de 6 tableaux vers des map nestées). Ce point est mineur vu que la transformation est linéaire, mais existe.

On pourrait imaginer un outil qui prend les 6 csv, génère une seule structure de données avec les markdown déjà transformés en HTML.

Un autre sujet à discuter, c'est les calculs financiers faits côté client pour chaque utilisateur. On pourrait les faire dans une étape de build.

**Comment by DavidBruant** [comment]
Par ailleurs, ces outils pourraient faire de la validation sur les données.

**Comment by thom4parisot** [comment]
Ouais ou jekyll en fait. Il lit les fichiers CSV et convertit le markdown en HTML :-p

https://jekyllrb.com/docs/datafiles/

Y'aurait qu'à stringifier le JSON et le placer dans des data attributes.

**Comment by DavidBruant** [comment]
A priori, ça ne sera pas nécessaire

**Comment by DavidBruant** [comment]
Et puis début 2018, on est passé aux fichiers XML et donc un tel outil a été créé à l'occasion (pour les données financières, pas les textuelles)
