### ISSUE TITLE
finances détails : Attribuer les dépenses aux dépenses et les recettes aux recettes

### ISSUE THREAD

**Issue by ClementineHahn** [datalocale/dataviz-finances-gironde#93]
en date du 07.04.17 :
 lors de la navigation dans le total des dépenses du département :
- les sections recettes mènent aux section dépenses 
- les sections dépenses menent aux recettes.

 Il faudrait rétablir les bons accès.

**Comment by DavidBruant** [comment]
Fait dans #97
